// Generated by CIRCT 10de20867
module ISAX_brimm(	// @[scheduling_solutions_0.mlir:2:3]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdInstr_cv_beqimm_3_i,
                     RdRS1_cv_beqimm_3_i,
                     RdPC_cv_beqimm_3_i,
  output wire [31:0] WrPC_cv_beqimm_3_o,
  output wire        WrPC_validReq_cv_beqimm_3_o,
  input  wire        RdStall_cv_beqimm_3_i,
                     RdIValid_cv_beqimm_3_i
);

  wire [31:0] _GEN;
  wire        _GEN_0;
  wire        _GEN_1 = clk_i;
  wire        _GEN_2 = rst_i;
  wire [31:0] _GEN_3 = RdInstr_cv_beqimm_3_i;
  wire [31:0] _GEN_4 = RdRS1_cv_beqimm_3_i;
  wire [31:0] _GEN_5 = RdPC_cv_beqimm_3_i;
  wire        _GEN_6 = RdStall_cv_beqimm_3_i;
  wire        _GEN_7;
  assign _GEN_7 = RdIValid_cv_beqimm_3_i;
  assign _GEN_7 = RdIValid_cv_beqimm_3_i;
  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("brimm.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_brimm_SharingGroup_1 inst_ISAX_brimm_SharingGroup_1 (
    .clk                         (_GEN_1),
    .rst                         (_GEN_2),
    .ready                       (/* unused */),
    .RdInstr_cv_beqimm_3_i       (_GEN_3),
    .RdRS1_cv_beqimm_3_i         (_GEN_4),
    .RdPC_cv_beqimm_3_i          (_GEN_5),
    .WrPC_cv_beqimm_3_o          (_GEN),
    .WrPC_validReq_cv_beqimm_3_o (_GEN_0),
    .RdStall_cv_beqimm_3_i       (_GEN_6),
    .RdIValid_cv_beqimm_3_i      (_GEN_7)
  );
  assign WrPC_cv_beqimm_3_o = _GEN;	// @[scheduling_solutions_0.mlir:2:3]
  assign WrPC_validReq_cv_beqimm_3_o = _GEN_0;	// @[scheduling_solutions_0.mlir:2:3]
endmodule

module ISAX_brimm_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdInstr_cv_beqimm_3_i,
                     RdRS1_cv_beqimm_3_i,
                     RdPC_cv_beqimm_3_i,
  output wire [31:0] WrPC_cv_beqimm_3_o,
  output wire        WrPC_validReq_cv_beqimm_3_o,
  input  wire        RdStall_cv_beqimm_3_i,
                     RdIValid_cv_beqimm_3_i
);

  wire        _GEN;
  wire [31:0] _GEN_0;
  assign _GEN =
    {1'h0,
     RdRS1_cv_beqimm_3_i} == /* LN_ID=13 PARENT_INST_NAME=[isax_brimm_inst_ISAX_brimm_SharingGroup_1] */ {{28{RdInstr_cv_beqimm_3_i[24]}},
                                                                                                          RdInstr_cv_beqimm_3_i[24:20]};	// @[scheduling_solutions_0.mlir:3:14, :50:16, :54:16, :55:17, :56:17, :57:17, :58:17]
  assign _GEN_0 =
    RdPC_cv_beqimm_3_i
    + /* LN_ID=17 PARENT_INST_NAME=[isax_brimm_inst_ISAX_brimm_SharingGroup_1] */ {{20{RdInstr_cv_beqimm_3_i[31]}},
                                                                                   RdInstr_cv_beqimm_3_i[7],
                                                                                   RdInstr_cv_beqimm_3_i[30:25],
                                                                                   RdInstr_cv_beqimm_3_i[11:8],
                                                                                   1'h0};	// @[scheduling_solutions_0.mlir:3:14, :48:16, :49:16, :51:16, :52:16, :60:17, :61:17, :62:17]
  wire        _GEN_1 = 1'h1;	// @[scheduling_solutions_0.mlir:4:13]
  assign ready = _GEN_1;
  assign WrPC_cv_beqimm_3_o = _GEN_0;
  assign WrPC_validReq_cv_beqimm_3_o = _GEN;
endmodule

