// Generated by CIRCT unknown git version
module ISAX_sqrt_decoupled(	// sqrt.mlir:1:1
  input         clk_i,
                rst_i,
  input  [31:0] RdRS1_sqrt_decoupled_3_i,
  input         WrRD_spawn_validResp_sqrt_decoupled_5_i,
                Commited_rd_spawn_WrRD_spawn_5_i,
                Commited_rd_spawn_validReq_WrRD_spawn_5_i,
                RdStall_sqrt_decoupled_3_i,
                RdStall_sqrt_decoupled_4_i,
  output [31:0] WrRD_spawn_sqrt_decoupled_5_o
);

  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("sqrt_decoupled.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  sqrt_decoupled inst_sqrt_decoupled (
    .clk         (clk_i),
    .rst         (rst_i),
    .arg1_2      (RdRS1_sqrt_decoupled_3_i),
    .stall_in_2  (RdStall_sqrt_decoupled_3_i),
    .stall_in_3  (RdStall_sqrt_decoupled_4_i),
    .res_12_data (WrRD_spawn_sqrt_decoupled_5_o)
  );
endmodule

module sqrt_decoupled(	// sqrt.mlir:3:3
  input         clk,
                rst,
  input  [31:0] arg1_2,
  input         stall_in_2,
                stall_in_3,
  output [31:0] res_12_data
);

  reg  [31:0] pipe_2;	// sqrt.mlir:19:18
  reg  [30:0] pipe_2_0;	// sqrt.mlir:19:18
  reg  [31:0] pipe_3;	// sqrt.mlir:19:18
  reg  [30:0] pipe_3_0;	// sqrt.mlir:19:18
  reg  [31:0] pipe_4;	// sqrt.mlir:19:18
  reg  [30:0] pipe_4_0;	// sqrt.mlir:19:18
  reg  [31:0] pipe_5;	// sqrt.mlir:19:18
  reg  [30:0] pipe_5_0;	// sqrt.mlir:19:18
  reg  [31:0] pipe_6;	// sqrt.mlir:19:18
  reg  [30:0] pipe_6_0;	// sqrt.mlir:19:18
  reg  [31:0] pipe_7;	// sqrt.mlir:19:18
  reg  [30:0] pipe_7_0;	// sqrt.mlir:19:18
  reg  [31:0] pipe_8;	// sqrt.mlir:19:18
  reg  [30:0] pipe_8_0;	// sqrt.mlir:19:18
  reg  [31:0] pipe_9;	// sqrt.mlir:19:18
  reg  [30:0] pipe_9_0;	// sqrt.mlir:19:18
  reg  [31:0] pipe_10;	// sqrt.mlir:19:18
  reg  [30:0] pipe_10_0;	// sqrt.mlir:19:18
  reg  [31:0] pipe_11;	// sqrt.mlir:19:18
  reg  [30:0] pipe_11_0;	// sqrt.mlir:19:18
  wire [31:0] _GEN = {|(arg1_2[31:30]), 31'h0};	// sqrt.mlir:8:10, :17:13, :19:18
  wire [30:0] _GEN_0 = (|(arg1_2[31:30])) ? arg1_2[30:0] - 31'h40000000 : arg1_2[30:0];	// sqrt.mlir:4:10, :17:13, :19:18, :20:15
  wire [31:0] _GEN_1 = _GEN + 32'h20000000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_2 = {_GEN_0, 1'h0} >= _GEN_1;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_3 = {_GEN_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_4 = _GEN_2 ? _GEN + 32'h40000000 : _GEN;	// sqrt.mlir:17:13, :19:18, :22:15
  wire [30:0] _GEN_5 = _GEN_2 ? _GEN_3 - _GEN_1[30:0] : _GEN_3;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_6 = _GEN_4 + 32'h10000000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_7 = {_GEN_5, 1'h0} >= _GEN_6;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_8 = {_GEN_5[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_9 = pipe_2 + 32'h8000000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_10 = {pipe_2_0, 1'h0} >= _GEN_9;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_11 = {pipe_2_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_12 = _GEN_10 ? pipe_2 + 32'h10000000 : pipe_2;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_13 = _GEN_10 ? _GEN_11 - _GEN_9[30:0] : _GEN_11;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_14 = _GEN_12 + 32'h4000000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_15 = {_GEN_13, 1'h0} >= _GEN_14;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_16 = {_GEN_13[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_17 = _GEN_15 ? _GEN_12 + 32'h8000000 : _GEN_12;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_18 = _GEN_15 ? _GEN_16 - _GEN_14[30:0] : _GEN_16;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_19 = _GEN_17 + 32'h2000000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_20 = {_GEN_18, 1'h0} >= _GEN_19;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_21 = {_GEN_18[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_22 = pipe_3 + 32'h1000000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_23 = {pipe_3_0, 1'h0} >= _GEN_22;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_24 = {pipe_3_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_25 = _GEN_23 ? pipe_3 + 32'h2000000 : pipe_3;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_26 = _GEN_23 ? _GEN_24 - _GEN_22[30:0] : _GEN_24;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_27 = _GEN_25 + 32'h800000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_28 = {_GEN_26, 1'h0} >= _GEN_27;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_29 = {_GEN_26[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_30 = _GEN_28 ? _GEN_25 + 32'h1000000 : _GEN_25;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_31 = _GEN_28 ? _GEN_29 - _GEN_27[30:0] : _GEN_29;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_32 = _GEN_30 + 32'h400000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_33 = {_GEN_31, 1'h0} >= _GEN_32;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_34 = {_GEN_31[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_35 = pipe_4 + 32'h200000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_36 = {pipe_4_0, 1'h0} >= _GEN_35;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_37 = {pipe_4_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_38 = _GEN_36 ? pipe_4 + 32'h400000 : pipe_4;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_39 = _GEN_36 ? _GEN_37 - _GEN_35[30:0] : _GEN_37;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_40 = _GEN_38 + 32'h100000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_41 = {_GEN_39, 1'h0} >= _GEN_40;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_42 = {_GEN_39[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_43 = _GEN_41 ? _GEN_38 + 32'h200000 : _GEN_38;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_44 = _GEN_41 ? _GEN_42 - _GEN_40[30:0] : _GEN_42;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_45 = _GEN_43 + 32'h80000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_46 = {_GEN_44, 1'h0} >= _GEN_45;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_47 = {_GEN_44[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_48 = pipe_5 + 32'h40000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_49 = {pipe_5_0, 1'h0} >= _GEN_48;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_50 = {pipe_5_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_51 = _GEN_49 ? pipe_5 + 32'h80000 : pipe_5;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_52 = _GEN_49 ? _GEN_50 - _GEN_48[30:0] : _GEN_50;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_53 = _GEN_51 + 32'h20000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_54 = {_GEN_52, 1'h0} >= _GEN_53;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_55 = {_GEN_52[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_56 = _GEN_54 ? _GEN_51 + 32'h40000 : _GEN_51;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_57 = _GEN_54 ? _GEN_55 - _GEN_53[30:0] : _GEN_55;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_58 = _GEN_56 + 32'h10000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_59 = {_GEN_57, 1'h0} >= _GEN_58;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_60 = {_GEN_57[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_61 = pipe_6 + 32'h8000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_62 = {pipe_6_0, 1'h0} >= _GEN_61;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_63 = {pipe_6_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_64 = _GEN_62 ? pipe_6 + 32'h10000 : pipe_6;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_65 = _GEN_62 ? _GEN_63 - _GEN_61[30:0] : _GEN_63;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_66 = _GEN_64 + 32'h4000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_67 = {_GEN_65, 1'h0} >= _GEN_66;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_68 = {_GEN_65[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_69 = _GEN_67 ? _GEN_64 + 32'h8000 : _GEN_64;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_70 = _GEN_67 ? _GEN_68 - _GEN_66[30:0] : _GEN_68;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_71 = _GEN_69 + 32'h2000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_72 = {_GEN_70, 1'h0} >= _GEN_71;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_73 = {_GEN_70[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_74 = pipe_7 + 32'h1000;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_75 = {pipe_7_0, 1'h0} >= _GEN_74;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_76 = {pipe_7_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_77 = _GEN_75 ? pipe_7 + 32'h2000 : pipe_7;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_78 = _GEN_75 ? _GEN_76 - _GEN_74[30:0] : _GEN_76;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_79 = _GEN_77 + 32'h800;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_80 = {_GEN_78, 1'h0} >= _GEN_79;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_81 = {_GEN_78[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_82 = _GEN_80 ? _GEN_77 + 32'h1000 : _GEN_77;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_83 = _GEN_80 ? _GEN_81 - _GEN_79[30:0] : _GEN_81;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_84 = _GEN_82 + 32'h400;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_85 = {_GEN_83, 1'h0} >= _GEN_84;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_86 = {_GEN_83[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_87 = pipe_8 + 32'h200;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_88 = {pipe_8_0, 1'h0} >= _GEN_87;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_89 = {pipe_8_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_90 = _GEN_88 ? pipe_8 + 32'h400 : pipe_8;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_91 = _GEN_88 ? _GEN_89 - _GEN_87[30:0] : _GEN_89;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_92 = _GEN_90 + 32'h100;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_93 = {_GEN_91, 1'h0} >= _GEN_92;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_94 = {_GEN_91[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_95 = _GEN_93 ? _GEN_90 + 32'h200 : _GEN_90;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_96 = _GEN_93 ? _GEN_94 - _GEN_92[30:0] : _GEN_94;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_97 = _GEN_95 + 32'h80;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_98 = {_GEN_96, 1'h0} >= _GEN_97;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_99 = {_GEN_96[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_100 = pipe_9 + 32'h40;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_101 = {pipe_9_0, 1'h0} >= _GEN_100;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_102 = {pipe_9_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_103 = _GEN_101 ? pipe_9 + 32'h80 : pipe_9;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_104 = _GEN_101 ? _GEN_102 - _GEN_100[30:0] : _GEN_102;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_105 = _GEN_103 + 32'h20;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_106 = {_GEN_104, 1'h0} >= _GEN_105;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_107 = {_GEN_104[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_108 = _GEN_106 ? _GEN_103 + 32'h40 : _GEN_103;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_109 = _GEN_106 ? _GEN_107 - _GEN_105[30:0] : _GEN_107;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_110 = _GEN_108 + 32'h10;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_111 = {_GEN_109, 1'h0} >= _GEN_110;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_112 = {_GEN_109[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_113 = pipe_10 + 32'h8;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_114 = {pipe_10_0, 1'h0} >= _GEN_113;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_115 = {pipe_10_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_116 = _GEN_114 ? pipe_10 + 32'h10 : pipe_10;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_117 = _GEN_114 ? _GEN_115 - _GEN_113[30:0] : _GEN_115;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_118 = _GEN_116 + 32'h4;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_119 = {_GEN_117, 1'h0} >= _GEN_118;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_120 = {_GEN_117[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_121 = _GEN_119 ? _GEN_116 + 32'h8 : _GEN_116;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_122 = _GEN_119 ? _GEN_120 - _GEN_118[30:0] : _GEN_120;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [31:0] _GEN_123 = _GEN_121 + 32'h2;	// sqrt.mlir:15:13, :19:18, :31:13
  wire        _GEN_124 = {_GEN_122, 1'h0} >= _GEN_123;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_125 = {_GEN_122[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  always_ff @(posedge clk) begin	// sqrt.mlir:19:18
    pipe_2 <= stall_in_2 ? pipe_2 : _GEN_7 ? _GEN_4 + 32'h20000000 : _GEN_4;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_2_0 <= stall_in_2 ? pipe_2_0 : _GEN_7 ? _GEN_8 - _GEN_6[30:0] : _GEN_8;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
    pipe_3 <= stall_in_3 ? pipe_3 : _GEN_20 ? _GEN_17 + 32'h4000000 : _GEN_17;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_3_0 <= stall_in_3 ? pipe_3_0 : _GEN_20 ? _GEN_21 - _GEN_19[30:0] : _GEN_21;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
    pipe_4 <= _GEN_33 ? _GEN_30 + 32'h800000 : _GEN_30;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_4_0 <= _GEN_33 ? _GEN_34 - _GEN_32[30:0] : _GEN_34;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
    pipe_5 <= _GEN_46 ? _GEN_43 + 32'h100000 : _GEN_43;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_5_0 <= _GEN_46 ? _GEN_47 - _GEN_45[30:0] : _GEN_47;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
    pipe_6 <= _GEN_59 ? _GEN_56 + 32'h20000 : _GEN_56;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_6_0 <= _GEN_59 ? _GEN_60 - _GEN_58[30:0] : _GEN_60;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
    pipe_7 <= _GEN_72 ? _GEN_69 + 32'h4000 : _GEN_69;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_7_0 <= _GEN_72 ? _GEN_73 - _GEN_71[30:0] : _GEN_73;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
    pipe_8 <= _GEN_85 ? _GEN_82 + 32'h800 : _GEN_82;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_8_0 <= _GEN_85 ? _GEN_86 - _GEN_84[30:0] : _GEN_86;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
    pipe_9 <= _GEN_98 ? _GEN_95 + 32'h100 : _GEN_95;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_9_0 <= _GEN_98 ? _GEN_99 - _GEN_97[30:0] : _GEN_99;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
    pipe_10 <= _GEN_111 ? _GEN_108 + 32'h20 : _GEN_108;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_10_0 <= _GEN_111 ? _GEN_112 - _GEN_110[30:0] : _GEN_112;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
    pipe_11 <= _GEN_124 ? _GEN_121 + 32'h4 : _GEN_121;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
    pipe_11_0 <= _GEN_124 ? _GEN_125 - _GEN_123[30:0] : _GEN_125;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  end // always_ff @(posedge)
  wire [31:0] _GEN_126 = pipe_11 + 32'h1;	// sqrt.mlir:15:13, :19:18, :29:13
  wire        _GEN_127 = {pipe_11_0, 1'h0} >= _GEN_126;	// sqrt.mlir:7:10, :15:13, :17:13, :19:18, :29:13
  wire [30:0] _GEN_128 = {pipe_11_0[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  wire [31:0] _GEN_129 = _GEN_127 ? pipe_11 + 32'h2 : pipe_11;	// sqrt.mlir:17:13, :19:18, :22:15, :31:13
  wire [30:0] _GEN_130 = _GEN_127 ? _GEN_128 - _GEN_126[30:0] : _GEN_128;	// sqrt.mlir:15:13, :17:13, :19:18, :20:15
  wire [30:0] _GEN_131 = {_GEN_130[29:0], 1'h0};	// sqrt.mlir:7:10, :19:18, :20:15
  assign res_12_data =
    {{_GEN_130, 1'h0} >= _GEN_129 ? _GEN_131 - _GEN_129[30:0] : _GEN_131, 1'h0} > _GEN_129
      ? _GEN_129 + 32'h1
      : _GEN_129;	// sqrt.mlir:3:3, :7:10, :17:13, :19:18, :20:15, :29:13, :34:11, :36:11, :38:13
endmodule

