// Generated by CIRCT unknown git version
module ISAX_sparkle(	// @[scheduling_solutions.mlir:2:3]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdRS1_sparkle_ell_4_i,
                     RdRS2_sparkle_ell_4_i,
  output wire [31:0] WrRD_sparkle_ell_4_o,
  input  wire        RdStall_sparkle_ell_4_i,
                     RdIValid_sparkle_ell_4_i,
  input  wire [31:0] RdInstr_sparkle_rcon_4_i,
                     RdRS1_sparkle_rcon_4_i,
  output wire [31:0] WrRD_sparkle_rcon_4_o,
  input  wire        RdStall_sparkle_rcon_4_i,
                     RdIValid_sparkle_rcon_4_i,
  input  wire [31:0] RdInstr_sparkle_whole_enci_x_4_i,
                     RdRS1_sparkle_whole_enci_x_4_i,
                     RdRS2_sparkle_whole_enci_x_4_i,
  output wire [31:0] WrRD_sparkle_whole_enci_x_4_o,
  input  wire        RdStall_sparkle_whole_enci_x_4_i,
                     RdIValid_sparkle_whole_enci_x_4_i,
  input  wire [31:0] RdInstr_sparkle_whole_enci_y_4_i,
                     RdRS1_sparkle_whole_enci_y_4_i,
                     RdRS2_sparkle_whole_enci_y_4_i,
  output wire [31:0] WrRD_sparkle_whole_enci_y_4_o,
  input  wire        RdStall_sparkle_whole_enci_y_4_i,
                     RdIValid_sparkle_whole_enci_y_4_i
);

  wire _GEN;
  wire _GEN_0;
  wire _GEN_1;
  wire _GEN_2;
  assign _GEN = RdIValid_sparkle_ell_4_i;
  assign _GEN_0 = RdIValid_sparkle_rcon_4_i;
  assign _GEN_1 = RdIValid_sparkle_whole_enci_x_4_i;
  assign _GEN_2 = RdIValid_sparkle_whole_enci_y_4_i;
  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("sparkle.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_sparkle_SharingGroup_1 inst_ISAX_sparkle_SharingGroup_1 (
    .clk                      (clk_i),
    .rst                      (rst_i),
    .ready                    (/* unused */),
    .RdRS1_sparkle_ell_4_i    (RdRS1_sparkle_ell_4_i),
    .RdRS2_sparkle_ell_4_i    (RdRS2_sparkle_ell_4_i),
    .WrRD_sparkle_ell_4_o     (WrRD_sparkle_ell_4_o),
    .RdStall_sparkle_ell_4_i  (RdStall_sparkle_ell_4_i),
    .RdIValid_sparkle_ell_4_i (_GEN)
  );
  ISAX_sparkle_SharingGroup_2 inst_ISAX_sparkle_SharingGroup_2 (
    .clk                       (clk_i),
    .rst                       (rst_i),
    .ready                     (/* unused */),
    .RdInstr_sparkle_rcon_4_i  (RdInstr_sparkle_rcon_4_i),
    .RdRS1_sparkle_rcon_4_i    (RdRS1_sparkle_rcon_4_i),
    .WrRD_sparkle_rcon_4_o     (WrRD_sparkle_rcon_4_o),
    .RdStall_sparkle_rcon_4_i  (RdStall_sparkle_rcon_4_i),
    .RdIValid_sparkle_rcon_4_i (_GEN_0)
  );
  ISAX_sparkle_SharingGroup_3 inst_ISAX_sparkle_SharingGroup_3 (
    .clk                               (clk_i),
    .rst                               (rst_i),
    .ready                             (/* unused */),
    .RdInstr_sparkle_whole_enci_x_4_i  (RdInstr_sparkle_whole_enci_x_4_i),
    .RdRS1_sparkle_whole_enci_x_4_i    (RdRS1_sparkle_whole_enci_x_4_i),
    .RdRS2_sparkle_whole_enci_x_4_i    (RdRS2_sparkle_whole_enci_x_4_i),
    .WrRD_sparkle_whole_enci_x_4_o     (WrRD_sparkle_whole_enci_x_4_o),
    .RdStall_sparkle_whole_enci_x_4_i  (RdStall_sparkle_whole_enci_x_4_i),
    .RdIValid_sparkle_whole_enci_x_4_i (_GEN_1)
  );
  ISAX_sparkle_SharingGroup_4 inst_ISAX_sparkle_SharingGroup_4 (
    .clk                               (clk_i),
    .rst                               (rst_i),
    .ready                             (/* unused */),
    .RdInstr_sparkle_whole_enci_y_4_i  (RdInstr_sparkle_whole_enci_y_4_i),
    .RdRS1_sparkle_whole_enci_y_4_i    (RdRS1_sparkle_whole_enci_y_4_i),
    .RdRS2_sparkle_whole_enci_y_4_i    (RdRS2_sparkle_whole_enci_y_4_i),
    .WrRD_sparkle_whole_enci_y_4_o     (WrRD_sparkle_whole_enci_y_4_o),
    .RdStall_sparkle_whole_enci_y_4_i  (RdStall_sparkle_whole_enci_y_4_i),
    .RdIValid_sparkle_whole_enci_y_4_i (_GEN_2)
  );
endmodule

module ISAX_sparkle_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdRS1_sparkle_ell_4_i,
                     RdRS2_sparkle_ell_4_i,
  output wire [31:0] WrRD_sparkle_ell_4_o,
  input  wire        RdStall_sparkle_ell_4_i,
                     RdIValid_sparkle_ell_4_i
);

  wire [31:0] _GEN = RdRS1_sparkle_ell_4_i ^ RdRS2_sparkle_ell_4_i;	// @[scheduling_solutions.mlir:176:16]
  wire [31:0] _GEN_0 = _GEN ^ {_GEN[15:0], 16'h0};	// @[scheduling_solutions.mlir:176:16, :177:16, :178:16, :179:16]
  assign ready = 1'h1;
  assign WrRD_sparkle_ell_4_o = {_GEN_0[15:0], _GEN_0[31:16]};	// @[scheduling_solutions.mlir:179:16, :180:16, :181:16, :182:16]
endmodule

module ISAX_sparkle_SharingGroup_2(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdInstr_sparkle_rcon_4_i,
                     RdRS1_sparkle_rcon_4_i,
  output wire [31:0] WrRD_sparkle_rcon_4_o,
  input  wire        RdStall_sparkle_rcon_4_i,
                     RdIValid_sparkle_rcon_4_i
);

  reg [31:0] casez_tmp;	// @[scheduling_solutions.mlir:33:16]
  always_comb begin
    casez (RdInstr_sparkle_rcon_4_i[27:25])	// @[scheduling_solutions.mlir:31:16]
      3'b000:
        casez_tmp = 32'hB7E15162;
      3'b001:
        casez_tmp = 32'hBF715880;
      3'b010:
        casez_tmp = 32'h38B4DA56;
      3'b011:
        casez_tmp = 32'h324E7738;
      3'b100:
        casez_tmp = 32'hBB1185EB;
      3'b101:
        casez_tmp = 32'h4F7C7B57;
      3'b110:
        casez_tmp = 32'hCFBFA1C8;
      default:
        casez_tmp = 32'hC2B3293D;
    endcase	// @[scheduling_solutions.mlir:31:16]
  end // always_comb
  assign ready = 1'h1;
  assign WrRD_sparkle_rcon_4_o = RdRS1_sparkle_rcon_4_i ^ casez_tmp;	// @[scheduling_solutions.mlir:33:16, :34:16]
endmodule

module ISAX_sparkle_SharingGroup_3(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdInstr_sparkle_whole_enci_x_4_i,
                     RdRS1_sparkle_whole_enci_x_4_i,
                     RdRS2_sparkle_whole_enci_x_4_i,
  output wire [31:0] WrRD_sparkle_whole_enci_x_4_o,
  input  wire        RdStall_sparkle_whole_enci_x_4_i,
                     RdIValid_sparkle_whole_enci_x_4_i
);

  reg  [31:0] casez_tmp;	// @[scheduling_solutions.mlir:251:16]
  always_comb begin
    casez (RdInstr_sparkle_whole_enci_x_4_i[27:25])	// @[scheduling_solutions.mlir:248:16]
      3'b000:
        casez_tmp = 32'hB7E15162;
      3'b001:
        casez_tmp = 32'hBF715880;
      3'b010:
        casez_tmp = 32'h38B4DA56;
      3'b011:
        casez_tmp = 32'h324E7738;
      3'b100:
        casez_tmp = 32'hBB1185EB;
      3'b101:
        casez_tmp = 32'h4F7C7B57;
      3'b110:
        casez_tmp = 32'hCFBFA1C8;
      default:
        casez_tmp = 32'hC2B3293D;
    endcase	// @[scheduling_solutions.mlir:248:16]
  end // always_comb
  wire [31:0] _GEN =
    RdRS1_sparkle_whole_enci_x_4_i
    + {RdRS2_sparkle_whole_enci_x_4_i[30:0], RdRS2_sparkle_whole_enci_x_4_i[31]};	// @[scheduling_solutions.mlir:252:16, :253:16, :254:16, :255:16]
  wire [31:0] _GEN_0 = RdRS2_sparkle_whole_enci_x_4_i ^ {_GEN[23:0], _GEN[31:24]};	// @[scheduling_solutions.mlir:255:16, :256:17, :257:17, :258:17, :259:17]
  wire [31:0] _GEN_1 = (_GEN ^ casez_tmp) + {_GEN_0[16:0], _GEN_0[31:17]};	// @[scheduling_solutions.mlir:251:16, :255:16, :259:17, :260:17, :261:17, :262:17, :263:17, :264:17]
  wire [31:0] _GEN_2 = _GEN_0 ^ {_GEN_1[16:0], _GEN_1[31:17]};	// @[scheduling_solutions.mlir:259:17, :264:17, :265:17, :266:17, :267:17, :268:17]
  wire [31:0] _GEN_3 = (_GEN_1 ^ casez_tmp) + _GEN_2;	// @[scheduling_solutions.mlir:251:16, :264:17, :268:17, :269:17, :270:17]
  wire [31:0] _GEN_4 = _GEN_2 ^ {_GEN_3[30:0], _GEN_3[31]};	// @[scheduling_solutions.mlir:268:17, :270:17, :271:17, :272:17, :273:17, :274:17]
  assign ready = 1'h1;
  assign WrRD_sparkle_whole_enci_x_4_o =
    (_GEN_3 ^ casez_tmp) + {_GEN_4[23:0], _GEN_4[31:24]} ^ casez_tmp;	// @[scheduling_solutions.mlir:251:16, :270:17, :274:17, :275:17, :276:17, :277:17, :278:17, :279:17, :280:17]
endmodule

module ISAX_sparkle_SharingGroup_4(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdInstr_sparkle_whole_enci_y_4_i,
                     RdRS1_sparkle_whole_enci_y_4_i,
                     RdRS2_sparkle_whole_enci_y_4_i,
  output wire [31:0] WrRD_sparkle_whole_enci_y_4_o,
  input  wire        RdStall_sparkle_whole_enci_y_4_i,
                     RdIValid_sparkle_whole_enci_y_4_i
);

  reg  [31:0] casez_tmp;	// @[scheduling_solutions.mlir:106:16]
  always_comb begin
    casez (RdInstr_sparkle_whole_enci_y_4_i[27:25])	// @[scheduling_solutions.mlir:103:16]
      3'b000:
        casez_tmp = 32'hB7E15162;
      3'b001:
        casez_tmp = 32'hBF715880;
      3'b010:
        casez_tmp = 32'h38B4DA56;
      3'b011:
        casez_tmp = 32'h324E7738;
      3'b100:
        casez_tmp = 32'hBB1185EB;
      3'b101:
        casez_tmp = 32'h4F7C7B57;
      3'b110:
        casez_tmp = 32'hCFBFA1C8;
      default:
        casez_tmp = 32'hC2B3293D;
    endcase	// @[scheduling_solutions.mlir:103:16]
  end // always_comb
  wire [31:0] _GEN =
    RdRS1_sparkle_whole_enci_y_4_i
    + {RdRS2_sparkle_whole_enci_y_4_i[30:0], RdRS2_sparkle_whole_enci_y_4_i[31]};	// @[scheduling_solutions.mlir:107:16, :108:16, :109:16, :110:16]
  wire [31:0] _GEN_0 = RdRS2_sparkle_whole_enci_y_4_i ^ {_GEN[23:0], _GEN[31:24]};	// @[scheduling_solutions.mlir:110:16, :111:17, :112:17, :113:17, :114:17]
  wire [31:0] _GEN_1 = (_GEN ^ casez_tmp) + {_GEN_0[16:0], _GEN_0[31:17]};	// @[scheduling_solutions.mlir:106:16, :110:16, :114:17, :115:17, :116:17, :117:17, :118:17, :119:17]
  wire [31:0] _GEN_2 = _GEN_0 ^ {_GEN_1[16:0], _GEN_1[31:17]};	// @[scheduling_solutions.mlir:114:17, :119:17, :120:17, :121:17, :122:17, :123:17]
  wire [31:0] _GEN_3 = (_GEN_1 ^ casez_tmp) + _GEN_2;	// @[scheduling_solutions.mlir:106:16, :119:17, :123:17, :124:17, :125:17]
  wire [31:0] _GEN_4 = _GEN_2 ^ {_GEN_3[30:0], _GEN_3[31]};	// @[scheduling_solutions.mlir:123:17, :125:17, :126:17, :127:17, :128:17, :129:17]
  wire [31:0] _GEN_5 = (_GEN_3 ^ casez_tmp) + {_GEN_4[23:0], _GEN_4[31:24]};	// @[scheduling_solutions.mlir:106:16, :125:17, :129:17, :130:17, :131:17, :132:17, :133:17, :134:17]
  assign ready = 1'h1;
  assign WrRD_sparkle_whole_enci_y_4_o = _GEN_4 ^ {_GEN_5[15:0], _GEN_5[31:16]};	// @[scheduling_solutions.mlir:129:17, :134:17, :135:17, :136:17, :137:17, :138:17]
endmodule

