// Generated by CIRCT unknown git version
module ISAX_autoinc(	// @[autoinc.mlir:1:1]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdRS1_setup_3_i,
  output wire [31:0] WrADDR_setup_3_o,
  output wire        WrADDR_validReq_setup_3_o,
  input  wire [31:0] RdRS2_setup_3_i,
  output wire [31:0] WrINCR_setup_3_o,
  output wire        WrINCR_validReq_setup_3_o,
  input  wire [31:0] RdADDR_lw_inc_4_i,
                     RdMem_lw_inc_4_i,
  output wire [31:0] RdMem_addr_lw_inc_4_o,
  output wire        RdMem_validReq_lw_inc_4_o,
  output wire [1:0]  RdMem_size_lw_inc_4_o,
  input  wire [31:0] RdINCR_lw_inc_4_i,
  output wire [31:0] WrADDR_lw_inc_4_o,
  output wire        WrADDR_validReq_lw_inc_4_o,
  output wire [31:0] WrRD_lw_inc_4_o,
  input  wire [31:0] RdADDR_sw_inc_4_i,
                     RdRS1_sw_inc_4_i,
  output wire [31:0] WrMem_addr_sw_inc_4_o,
                     WrMem_sw_inc_4_o,
  output wire        WrMem_validReq_sw_inc_4_o,
  output wire [1:0]  WrMem_size_sw_inc_4_o,
  input  wire [31:0] RdINCR_sw_inc_4_i,
  output wire [31:0] WrADDR_sw_inc_4_o,
  output wire        WrADDR_validReq_sw_inc_4_o
);

  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("autoinc.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_autoinc_SharingGroup_1 inst_ISAX_autoinc_SharingGroup_1 (
    .clk                       (clk_i),
    .rst                       (rst_i),
    .ready                     (/* unused */),
    .RdRS1_setup_3_i           (RdRS1_setup_3_i),
    .WrADDR_setup_3_o          (WrADDR_setup_3_o),
    .WrADDR_validReq_setup_3_o (WrADDR_validReq_setup_3_o),
    .RdRS2_setup_3_i           (RdRS2_setup_3_i),
    .WrINCR_setup_3_o          (WrINCR_setup_3_o),
    .WrINCR_validReq_setup_3_o (WrINCR_validReq_setup_3_o)
  );
  ISAX_autoinc_SharingGroup_2 inst_ISAX_autoinc_SharingGroup_2 (
    .clk                        (clk_i),
    .rst                        (rst_i),
    .ready                      (/* unused */),
    .RdADDR_lw_inc_4_i          (RdADDR_lw_inc_4_i),
    .RdMem_lw_inc_4_i           (RdMem_lw_inc_4_i),
    .RdMem_addr_lw_inc_4_o      (RdMem_addr_lw_inc_4_o),
    .RdMem_validReq_lw_inc_4_o  (RdMem_validReq_lw_inc_4_o),
    .RdMem_size_lw_inc_4_o      (RdMem_size_lw_inc_4_o),
    .RdINCR_lw_inc_4_i          (RdINCR_lw_inc_4_i),
    .WrADDR_lw_inc_4_o          (WrADDR_lw_inc_4_o),
    .WrADDR_validReq_lw_inc_4_o (WrADDR_validReq_lw_inc_4_o),
    .WrRD_lw_inc_4_o            (WrRD_lw_inc_4_o)
  );
  ISAX_autoinc_SharingGroup_3 inst_ISAX_autoinc_SharingGroup_3 (
    .clk                        (clk_i),
    .rst                        (rst_i),
    .ready                      (/* unused */),
    .RdADDR_sw_inc_4_i          (RdADDR_sw_inc_4_i),
    .RdRS1_sw_inc_4_i           (RdRS1_sw_inc_4_i),
    .WrMem_addr_sw_inc_4_o      (WrMem_addr_sw_inc_4_o),
    .WrMem_sw_inc_4_o           (WrMem_sw_inc_4_o),
    .WrMem_validReq_sw_inc_4_o  (WrMem_validReq_sw_inc_4_o),
    .WrMem_size_sw_inc_4_o      (WrMem_size_sw_inc_4_o),
    .RdINCR_sw_inc_4_i          (RdINCR_sw_inc_4_i),
    .WrADDR_sw_inc_4_o          (WrADDR_sw_inc_4_o),
    .WrADDR_validReq_sw_inc_4_o (WrADDR_validReq_sw_inc_4_o)
  );
endmodule

module ISAX_autoinc_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdRS1_setup_3_i,
  output wire [31:0] WrADDR_setup_3_o,
  output wire        WrADDR_validReq_setup_3_o,
  input  wire [31:0] RdRS2_setup_3_i,
  output wire [31:0] WrINCR_setup_3_o,
  output wire        WrINCR_validReq_setup_3_o
);

  assign ready = 1'h1;
  assign WrADDR_setup_3_o = RdRS1_setup_3_i;
  assign WrADDR_validReq_setup_3_o = 1'h1;
  assign WrINCR_setup_3_o = RdRS2_setup_3_i;
  assign WrINCR_validReq_setup_3_o = 1'h1;
endmodule

module ISAX_autoinc_SharingGroup_2(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdADDR_lw_inc_4_i,
                     RdMem_lw_inc_4_i,
  output wire [31:0] RdMem_addr_lw_inc_4_o,
  output wire        RdMem_validReq_lw_inc_4_o,
  output wire [1:0]  RdMem_size_lw_inc_4_o,
  input  wire [31:0] RdINCR_lw_inc_4_i,
  output wire [31:0] WrADDR_lw_inc_4_o,
  output wire        WrADDR_validReq_lw_inc_4_o,
  output wire [31:0] WrRD_lw_inc_4_o
);

  assign ready = 1'h1;
  assign RdMem_addr_lw_inc_4_o = RdADDR_lw_inc_4_i;
  assign RdMem_validReq_lw_inc_4_o = 1'h1;
  assign RdMem_size_lw_inc_4_o = 2'h2;
  assign WrADDR_lw_inc_4_o = RdADDR_lw_inc_4_i + RdINCR_lw_inc_4_i;	// @[autoinc.mlir:21:10]
  assign WrADDR_validReq_lw_inc_4_o = 1'h1;
  assign WrRD_lw_inc_4_o = RdMem_lw_inc_4_i;
endmodule

module ISAX_autoinc_SharingGroup_3(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdADDR_sw_inc_4_i,
                     RdRS1_sw_inc_4_i,
  output wire [31:0] WrMem_addr_sw_inc_4_o,
                     WrMem_sw_inc_4_o,
  output wire        WrMem_validReq_sw_inc_4_o,
  output wire [1:0]  WrMem_size_sw_inc_4_o,
  input  wire [31:0] RdINCR_sw_inc_4_i,
  output wire [31:0] WrADDR_sw_inc_4_o,
  output wire        WrADDR_validReq_sw_inc_4_o
);

  assign ready = 1'h1;
  assign WrMem_addr_sw_inc_4_o = RdADDR_sw_inc_4_i;
  assign WrMem_sw_inc_4_o = RdRS1_sw_inc_4_i;
  assign WrMem_validReq_sw_inc_4_o = 1'h1;
  assign WrMem_size_sw_inc_4_o = 2'h2;
  assign WrADDR_sw_inc_4_o = RdADDR_sw_inc_4_i + RdINCR_sw_inc_4_i;	// @[autoinc.mlir:34:10]
  assign WrADDR_validReq_sw_inc_4_o = 1'h1;
endmodule

