// Generated by CIRCT unknown git version
module ISAX_indirectjmp(	// @[scheduling_solutions.mlir:2:3]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdInstr_ijmp_4_i,
                     RdRS1_ijmp_4_i,
                     RdMem_ijmp_4_i,
  output wire [31:0] RdMem_addr_ijmp_4_o,
  output wire        RdMem_validReq_ijmp_4_o,
  output wire [1:0]  RdMem_size_ijmp_4_o,
  output wire [31:0] WrPC_ijmp_4_o,
  input  wire        RdStall_ijmp_4_i,
                     RdIValid_ijmp_4_i
);

  wire _GEN;
  assign _GEN = RdIValid_ijmp_4_i;
  assign _GEN = RdIValid_ijmp_4_i;
  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("indirectjmp.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_indirectjmp_SharingGroup_1 inst_ISAX_indirectjmp_SharingGroup_1 (
    .clk                     (clk_i),
    .rst                     (rst_i),
    .ready                   (/* unused */),
    .RdInstr_ijmp_4_i        (RdInstr_ijmp_4_i),
    .RdRS1_ijmp_4_i          (RdRS1_ijmp_4_i),
    .RdMem_ijmp_4_i          (RdMem_ijmp_4_i),
    .RdMem_addr_ijmp_4_o     (RdMem_addr_ijmp_4_o),
    .RdMem_validReq_ijmp_4_o (RdMem_validReq_ijmp_4_o),
    .RdMem_size_ijmp_4_o     (RdMem_size_ijmp_4_o),
    .WrPC_ijmp_4_o           (WrPC_ijmp_4_o),
    .RdStall_ijmp_4_i        (RdStall_ijmp_4_i),
    .RdIValid_ijmp_4_i       (_GEN)
  );
endmodule

module ISAX_indirectjmp_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdInstr_ijmp_4_i,
                     RdRS1_ijmp_4_i,
                     RdMem_ijmp_4_i,
  output wire [31:0] RdMem_addr_ijmp_4_o,
  output wire        RdMem_validReq_ijmp_4_o,
  output wire [1:0]  RdMem_size_ijmp_4_o,
  output wire [31:0] WrPC_ijmp_4_o,
  input  wire        RdStall_ijmp_4_i,
                     RdIValid_ijmp_4_i
);

  assign ready = 1'h1;
  assign RdMem_addr_ijmp_4_o = RdRS1_ijmp_4_i + {20'h0, RdInstr_ijmp_4_i[31:20]};	// @[scheduling_solutions.mlir:32:16, :34:16, :35:16]
  assign RdMem_validReq_ijmp_4_o = 1'h1;
  assign RdMem_size_ijmp_4_o = 2'h2;
  assign WrPC_ijmp_4_o = RdMem_ijmp_4_i;
endmodule

