// Generated by CIRCT unknown git version
module ISAX_sbox(	// @[scheduling_solutions.mlir:2:3]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdRS1_sbox_4_i,
  output wire [31:0] WrRD_sbox_4_o,
  input  wire        RdStall_sbox_4_i,
                     RdIValid_sbox_4_i
);

  wire _GEN;
  assign _GEN = RdIValid_sbox_4_i;
  assign _GEN = RdIValid_sbox_4_i;
  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("sbox.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_sbox_SharingGroup_1 inst_ISAX_sbox_SharingGroup_1 (
    .clk               (clk_i),
    .rst               (rst_i),
    .ready             (/* unused */),
    .RdRS1_sbox_4_i    (RdRS1_sbox_4_i),
    .WrRD_sbox_4_o     (WrRD_sbox_4_o),
    .RdStall_sbox_4_i  (RdStall_sbox_4_i),
    .RdIValid_sbox_4_i (_GEN)
  );
endmodule

module ISAX_sbox_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdRS1_sbox_4_i,
  output wire [31:0] WrRD_sbox_4_o,
  input  wire        RdStall_sbox_4_i,
                     RdIValid_sbox_4_i
);

  reg [7:0] casez_tmp;	// @[scheduling_solutions.mlir:30:16]
  always_comb begin
    casez (RdRS1_sbox_4_i[7:0])	// @[scheduling_solutions.mlir:29:16]
      8'b00000000:
        casez_tmp = 8'h63;
      8'b00000001:
        casez_tmp = 8'h7C;
      8'b00000010:
        casez_tmp = 8'h77;
      8'b00000011:
        casez_tmp = 8'h7B;
      8'b00000100:
        casez_tmp = 8'hF2;
      8'b00000101:
        casez_tmp = 8'h6B;
      8'b00000110:
        casez_tmp = 8'h6F;
      8'b00000111:
        casez_tmp = 8'hC5;
      8'b00001000:
        casez_tmp = 8'h30;
      8'b00001001:
        casez_tmp = 8'h1;
      8'b00001010:
        casez_tmp = 8'h67;
      8'b00001011:
        casez_tmp = 8'h2B;
      8'b00001100:
        casez_tmp = 8'hFE;
      8'b00001101:
        casez_tmp = 8'hD7;
      8'b00001110:
        casez_tmp = 8'hAB;
      8'b00001111:
        casez_tmp = 8'h76;
      8'b00010000:
        casez_tmp = 8'hCA;
      8'b00010001:
        casez_tmp = 8'h82;
      8'b00010010:
        casez_tmp = 8'hC9;
      8'b00010011:
        casez_tmp = 8'h7D;
      8'b00010100:
        casez_tmp = 8'hFA;
      8'b00010101:
        casez_tmp = 8'h59;
      8'b00010110:
        casez_tmp = 8'h47;
      8'b00010111:
        casez_tmp = 8'hF0;
      8'b00011000:
        casez_tmp = 8'hAD;
      8'b00011001:
        casez_tmp = 8'hD4;
      8'b00011010:
        casez_tmp = 8'hA2;
      8'b00011011:
        casez_tmp = 8'hAF;
      8'b00011100:
        casez_tmp = 8'h9C;
      8'b00011101:
        casez_tmp = 8'hA4;
      8'b00011110:
        casez_tmp = 8'h72;
      8'b00011111:
        casez_tmp = 8'hC0;
      8'b00100000:
        casez_tmp = 8'hB7;
      8'b00100001:
        casez_tmp = 8'hFD;
      8'b00100010:
        casez_tmp = 8'h93;
      8'b00100011:
        casez_tmp = 8'h26;
      8'b00100100:
        casez_tmp = 8'h36;
      8'b00100101:
        casez_tmp = 8'h3F;
      8'b00100110:
        casez_tmp = 8'hF7;
      8'b00100111:
        casez_tmp = 8'hCC;
      8'b00101000:
        casez_tmp = 8'h34;
      8'b00101001:
        casez_tmp = 8'hA5;
      8'b00101010:
        casez_tmp = 8'hE5;
      8'b00101011:
        casez_tmp = 8'hF1;
      8'b00101100:
        casez_tmp = 8'h71;
      8'b00101101:
        casez_tmp = 8'hD8;
      8'b00101110:
        casez_tmp = 8'h31;
      8'b00101111:
        casez_tmp = 8'h15;
      8'b00110000:
        casez_tmp = 8'h4;
      8'b00110001:
        casez_tmp = 8'hC7;
      8'b00110010:
        casez_tmp = 8'h23;
      8'b00110011:
        casez_tmp = 8'hC3;
      8'b00110100:
        casez_tmp = 8'h18;
      8'b00110101:
        casez_tmp = 8'h96;
      8'b00110110:
        casez_tmp = 8'h5;
      8'b00110111:
        casez_tmp = 8'h9A;
      8'b00111000:
        casez_tmp = 8'h7;
      8'b00111001:
        casez_tmp = 8'h12;
      8'b00111010:
        casez_tmp = 8'h80;
      8'b00111011:
        casez_tmp = 8'hE2;
      8'b00111100:
        casez_tmp = 8'hEB;
      8'b00111101:
        casez_tmp = 8'h27;
      8'b00111110:
        casez_tmp = 8'hB2;
      8'b00111111:
        casez_tmp = 8'h75;
      8'b01000000:
        casez_tmp = 8'h9;
      8'b01000001:
        casez_tmp = 8'h83;
      8'b01000010:
        casez_tmp = 8'h2C;
      8'b01000011:
        casez_tmp = 8'h1A;
      8'b01000100:
        casez_tmp = 8'h1B;
      8'b01000101:
        casez_tmp = 8'h6E;
      8'b01000110:
        casez_tmp = 8'h5A;
      8'b01000111:
        casez_tmp = 8'hA0;
      8'b01001000:
        casez_tmp = 8'h52;
      8'b01001001:
        casez_tmp = 8'h3B;
      8'b01001010:
        casez_tmp = 8'hD6;
      8'b01001011:
        casez_tmp = 8'hB3;
      8'b01001100:
        casez_tmp = 8'h29;
      8'b01001101:
        casez_tmp = 8'hE3;
      8'b01001110:
        casez_tmp = 8'h2F;
      8'b01001111:
        casez_tmp = 8'h84;
      8'b01010000:
        casez_tmp = 8'h53;
      8'b01010001:
        casez_tmp = 8'hD1;
      8'b01010010:
        casez_tmp = 8'h0;
      8'b01010011:
        casez_tmp = 8'hED;
      8'b01010100:
        casez_tmp = 8'h20;
      8'b01010101:
        casez_tmp = 8'hFC;
      8'b01010110:
        casez_tmp = 8'hB1;
      8'b01010111:
        casez_tmp = 8'h5B;
      8'b01011000:
        casez_tmp = 8'h6A;
      8'b01011001:
        casez_tmp = 8'hCB;
      8'b01011010:
        casez_tmp = 8'hBE;
      8'b01011011:
        casez_tmp = 8'h39;
      8'b01011100:
        casez_tmp = 8'h4A;
      8'b01011101:
        casez_tmp = 8'h4C;
      8'b01011110:
        casez_tmp = 8'h58;
      8'b01011111:
        casez_tmp = 8'hCF;
      8'b01100000:
        casez_tmp = 8'hD0;
      8'b01100001:
        casez_tmp = 8'hEF;
      8'b01100010:
        casez_tmp = 8'hAA;
      8'b01100011:
        casez_tmp = 8'hFB;
      8'b01100100:
        casez_tmp = 8'h43;
      8'b01100101:
        casez_tmp = 8'h4D;
      8'b01100110:
        casez_tmp = 8'h33;
      8'b01100111:
        casez_tmp = 8'h85;
      8'b01101000:
        casez_tmp = 8'h45;
      8'b01101001:
        casez_tmp = 8'hF9;
      8'b01101010:
        casez_tmp = 8'h2;
      8'b01101011:
        casez_tmp = 8'h7F;
      8'b01101100:
        casez_tmp = 8'h50;
      8'b01101101:
        casez_tmp = 8'h3C;
      8'b01101110:
        casez_tmp = 8'h9F;
      8'b01101111:
        casez_tmp = 8'hA8;
      8'b01110000:
        casez_tmp = 8'h51;
      8'b01110001:
        casez_tmp = 8'hA3;
      8'b01110010:
        casez_tmp = 8'h40;
      8'b01110011:
        casez_tmp = 8'h8F;
      8'b01110100:
        casez_tmp = 8'h92;
      8'b01110101:
        casez_tmp = 8'h9D;
      8'b01110110:
        casez_tmp = 8'h38;
      8'b01110111:
        casez_tmp = 8'hF5;
      8'b01111000:
        casez_tmp = 8'hBC;
      8'b01111001:
        casez_tmp = 8'hB6;
      8'b01111010:
        casez_tmp = 8'hDA;
      8'b01111011:
        casez_tmp = 8'h21;
      8'b01111100:
        casez_tmp = 8'h10;
      8'b01111101:
        casez_tmp = 8'hFF;
      8'b01111110:
        casez_tmp = 8'hF3;
      8'b01111111:
        casez_tmp = 8'hD2;
      8'b10000000:
        casez_tmp = 8'hCD;
      8'b10000001:
        casez_tmp = 8'hC;
      8'b10000010:
        casez_tmp = 8'h13;
      8'b10000011:
        casez_tmp = 8'hEC;
      8'b10000100:
        casez_tmp = 8'h5F;
      8'b10000101:
        casez_tmp = 8'h97;
      8'b10000110:
        casez_tmp = 8'h44;
      8'b10000111:
        casez_tmp = 8'h17;
      8'b10001000:
        casez_tmp = 8'hC4;
      8'b10001001:
        casez_tmp = 8'hA7;
      8'b10001010:
        casez_tmp = 8'h7E;
      8'b10001011:
        casez_tmp = 8'h3D;
      8'b10001100:
        casez_tmp = 8'h64;
      8'b10001101:
        casez_tmp = 8'h5D;
      8'b10001110:
        casez_tmp = 8'h19;
      8'b10001111:
        casez_tmp = 8'h73;
      8'b10010000:
        casez_tmp = 8'h60;
      8'b10010001:
        casez_tmp = 8'h81;
      8'b10010010:
        casez_tmp = 8'h4F;
      8'b10010011:
        casez_tmp = 8'hDC;
      8'b10010100:
        casez_tmp = 8'h22;
      8'b10010101:
        casez_tmp = 8'h2A;
      8'b10010110:
        casez_tmp = 8'h90;
      8'b10010111:
        casez_tmp = 8'h88;
      8'b10011000:
        casez_tmp = 8'h46;
      8'b10011001:
        casez_tmp = 8'hEE;
      8'b10011010:
        casez_tmp = 8'hB8;
      8'b10011011:
        casez_tmp = 8'h14;
      8'b10011100:
        casez_tmp = 8'hDE;
      8'b10011101:
        casez_tmp = 8'h5E;
      8'b10011110:
        casez_tmp = 8'hB;
      8'b10011111:
        casez_tmp = 8'hDB;
      8'b10100000:
        casez_tmp = 8'hE0;
      8'b10100001:
        casez_tmp = 8'h32;
      8'b10100010:
        casez_tmp = 8'h3A;
      8'b10100011:
        casez_tmp = 8'hA;
      8'b10100100:
        casez_tmp = 8'h49;
      8'b10100101:
        casez_tmp = 8'h6;
      8'b10100110:
        casez_tmp = 8'h24;
      8'b10100111:
        casez_tmp = 8'h5C;
      8'b10101000:
        casez_tmp = 8'hC2;
      8'b10101001:
        casez_tmp = 8'hD3;
      8'b10101010:
        casez_tmp = 8'hAC;
      8'b10101011:
        casez_tmp = 8'h62;
      8'b10101100:
        casez_tmp = 8'h91;
      8'b10101101:
        casez_tmp = 8'h95;
      8'b10101110:
        casez_tmp = 8'hE4;
      8'b10101111:
        casez_tmp = 8'h79;
      8'b10110000:
        casez_tmp = 8'hE7;
      8'b10110001:
        casez_tmp = 8'hC8;
      8'b10110010:
        casez_tmp = 8'h37;
      8'b10110011:
        casez_tmp = 8'h6D;
      8'b10110100:
        casez_tmp = 8'h8D;
      8'b10110101:
        casez_tmp = 8'hD5;
      8'b10110110:
        casez_tmp = 8'h4E;
      8'b10110111:
        casez_tmp = 8'hA9;
      8'b10111000:
        casez_tmp = 8'h6C;
      8'b10111001:
        casez_tmp = 8'h56;
      8'b10111010:
        casez_tmp = 8'hF4;
      8'b10111011:
        casez_tmp = 8'hEA;
      8'b10111100:
        casez_tmp = 8'h65;
      8'b10111101:
        casez_tmp = 8'h7A;
      8'b10111110:
        casez_tmp = 8'hAE;
      8'b10111111:
        casez_tmp = 8'h8;
      8'b11000000:
        casez_tmp = 8'hBA;
      8'b11000001:
        casez_tmp = 8'h78;
      8'b11000010:
        casez_tmp = 8'h25;
      8'b11000011:
        casez_tmp = 8'h2E;
      8'b11000100:
        casez_tmp = 8'h1C;
      8'b11000101:
        casez_tmp = 8'hA6;
      8'b11000110:
        casez_tmp = 8'hB4;
      8'b11000111:
        casez_tmp = 8'hC6;
      8'b11001000:
        casez_tmp = 8'hE8;
      8'b11001001:
        casez_tmp = 8'hDD;
      8'b11001010:
        casez_tmp = 8'h74;
      8'b11001011:
        casez_tmp = 8'h1F;
      8'b11001100:
        casez_tmp = 8'h4B;
      8'b11001101:
        casez_tmp = 8'hBD;
      8'b11001110:
        casez_tmp = 8'h8B;
      8'b11001111:
        casez_tmp = 8'h8A;
      8'b11010000:
        casez_tmp = 8'h70;
      8'b11010001:
        casez_tmp = 8'h3E;
      8'b11010010:
        casez_tmp = 8'hB5;
      8'b11010011:
        casez_tmp = 8'h66;
      8'b11010100:
        casez_tmp = 8'h48;
      8'b11010101:
        casez_tmp = 8'h3;
      8'b11010110:
        casez_tmp = 8'hF6;
      8'b11010111:
        casez_tmp = 8'hE;
      8'b11011000:
        casez_tmp = 8'h61;
      8'b11011001:
        casez_tmp = 8'h35;
      8'b11011010:
        casez_tmp = 8'h57;
      8'b11011011:
        casez_tmp = 8'hB9;
      8'b11011100:
        casez_tmp = 8'h86;
      8'b11011101:
        casez_tmp = 8'hC1;
      8'b11011110:
        casez_tmp = 8'h1D;
      8'b11011111:
        casez_tmp = 8'h9E;
      8'b11100000:
        casez_tmp = 8'hE1;
      8'b11100001:
        casez_tmp = 8'hF8;
      8'b11100010:
        casez_tmp = 8'h98;
      8'b11100011:
        casez_tmp = 8'h11;
      8'b11100100:
        casez_tmp = 8'h69;
      8'b11100101:
        casez_tmp = 8'hD9;
      8'b11100110:
        casez_tmp = 8'h8E;
      8'b11100111:
        casez_tmp = 8'h94;
      8'b11101000:
        casez_tmp = 8'h9B;
      8'b11101001:
        casez_tmp = 8'h1E;
      8'b11101010:
        casez_tmp = 8'h87;
      8'b11101011:
        casez_tmp = 8'hE9;
      8'b11101100:
        casez_tmp = 8'hCE;
      8'b11101101:
        casez_tmp = 8'h55;
      8'b11101110:
        casez_tmp = 8'h28;
      8'b11101111:
        casez_tmp = 8'hDF;
      8'b11110000:
        casez_tmp = 8'h8C;
      8'b11110001:
        casez_tmp = 8'hA1;
      8'b11110010:
        casez_tmp = 8'h89;
      8'b11110011:
        casez_tmp = 8'hD;
      8'b11110100:
        casez_tmp = 8'hBF;
      8'b11110101:
        casez_tmp = 8'hE6;
      8'b11110110:
        casez_tmp = 8'h42;
      8'b11110111:
        casez_tmp = 8'h68;
      8'b11111000:
        casez_tmp = 8'h41;
      8'b11111001:
        casez_tmp = 8'h99;
      8'b11111010:
        casez_tmp = 8'h2D;
      8'b11111011:
        casez_tmp = 8'hF;
      8'b11111100:
        casez_tmp = 8'hB0;
      8'b11111101:
        casez_tmp = 8'h54;
      8'b11111110:
        casez_tmp = 8'hBB;
      default:
        casez_tmp = 8'h16;
    endcase	// @[scheduling_solutions.mlir:29:16]
  end // always_comb
  assign ready = 1'h1;
  assign WrRD_sbox_4_o = {24'h0, casez_tmp};	// @[scheduling_solutions.mlir:30:16, :31:16]
endmodule

