// Generated by CIRCT unknown git version
module ISAX_zol(	// @[scheduling_solutions.mlir:2:3]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdInstr_setup_zol_3_i,
                     RdPC_setup_zol_3_i,
  output wire [31:0] WrZOLSTARTPC_setup_zol_3_o,
  output wire        WrZOLSTARTPC_validReq_setup_zol_3_o,
  output wire [31:0] WrZOLENDPC_setup_zol_3_o,
  output wire        WrZOLENDPC_validReq_setup_zol_3_o,
  output wire [31:0] WrZOLCOUNTER_setup_zol_3_o,
  output wire        WrZOLCOUNTER_validReq_setup_zol_3_o,
  input  wire        RdStall_setup_zol_3_i,
                     RdIValid_setup_zol_3_i,
  input  wire [31:0] RdZOLCOUNTER_zol_0_i,
                     RdZOLENDPC_zol_0_i,
                     RdPC_zol_0_i,
                     RdZOLSTARTPC_zol_0_i,
  output wire [31:0] WrPC_zol_0_o,
  output wire        WrPC_validReq_zol_0_o,
  output wire [31:0] WrZOLCOUNTER_zol_0_o,
  output wire        WrZOLCOUNTER_validReq_zol_0_o
);

  wire _GEN;
  assign _GEN = RdIValid_setup_zol_3_i;
  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("zol.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_zol_SharingGroup_1 inst_ISAX_zol_SharingGroup_1 (
    .clk                                 (clk_i),
    .rst                                 (rst_i),
    .ready                               (/* unused */),
    .RdInstr_setup_zol_3_i               (RdInstr_setup_zol_3_i),
    .RdPC_setup_zol_3_i                  (RdPC_setup_zol_3_i),
    .WrZOLSTARTPC_setup_zol_3_o          (WrZOLSTARTPC_setup_zol_3_o),
    .WrZOLSTARTPC_validReq_setup_zol_3_o (WrZOLSTARTPC_validReq_setup_zol_3_o),
    .WrZOLENDPC_setup_zol_3_o            (WrZOLENDPC_setup_zol_3_o),
    .WrZOLENDPC_validReq_setup_zol_3_o   (WrZOLENDPC_validReq_setup_zol_3_o),
    .WrZOLCOUNTER_setup_zol_3_o          (WrZOLCOUNTER_setup_zol_3_o),
    .WrZOLCOUNTER_validReq_setup_zol_3_o (WrZOLCOUNTER_validReq_setup_zol_3_o),
    .RdStall_setup_zol_3_i               (RdStall_setup_zol_3_i),
    .RdIValid_setup_zol_3_i              (_GEN)
  );
  ISAX_zol_SharingGroup_2 inst_ISAX_zol_SharingGroup_2 (
    .clk                           (clk_i),
    .rst                           (rst_i),
    .ready                         (/* unused */),
    .RdZOLCOUNTER_zol_0_i          (RdZOLCOUNTER_zol_0_i),
    .RdZOLENDPC_zol_0_i            (RdZOLENDPC_zol_0_i),
    .RdPC_zol_0_i                  (RdPC_zol_0_i),
    .RdZOLSTARTPC_zol_0_i          (RdZOLSTARTPC_zol_0_i),
    .WrPC_zol_0_o                  (WrPC_zol_0_o),
    .WrPC_validReq_zol_0_o         (WrPC_validReq_zol_0_o),
    .WrZOLCOUNTER_zol_0_o          (WrZOLCOUNTER_zol_0_o),
    .WrZOLCOUNTER_validReq_zol_0_o (WrZOLCOUNTER_validReq_zol_0_o)
  );
endmodule

module ISAX_zol_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdInstr_setup_zol_3_i,
                     RdPC_setup_zol_3_i,
  output wire [31:0] WrZOLSTARTPC_setup_zol_3_o,
  output wire        WrZOLSTARTPC_validReq_setup_zol_3_o,
  output wire [31:0] WrZOLENDPC_setup_zol_3_o,
  output wire        WrZOLENDPC_validReq_setup_zol_3_o,
  output wire [31:0] WrZOLCOUNTER_setup_zol_3_o,
  output wire        WrZOLCOUNTER_validReq_setup_zol_3_o,
  input  wire        RdStall_setup_zol_3_i,
                     RdIValid_setup_zol_3_i
);

  assign ready = 1'h1;
  assign WrZOLSTARTPC_setup_zol_3_o = RdPC_setup_zol_3_i + 32'h4;	// @[scheduling_solutions.mlir:53:16]
  assign WrZOLSTARTPC_validReq_setup_zol_3_o = 1'h1;
  assign WrZOLENDPC_setup_zol_3_o =
    RdPC_setup_zol_3_i + {26'h0, RdInstr_setup_zol_3_i[19:15], 1'h0};	// @[scheduling_solutions.mlir:51:16, :56:16, :57:16]
  assign WrZOLENDPC_validReq_setup_zol_3_o = 1'h1;
  assign WrZOLCOUNTER_setup_zol_3_o = {20'h0, RdInstr_setup_zol_3_i[31:20]};	// @[scheduling_solutions.mlir:50:16, :60:17]
  assign WrZOLCOUNTER_validReq_setup_zol_3_o = 1'h1;
endmodule

module ISAX_zol_SharingGroup_2(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdZOLCOUNTER_zol_0_i,
                     RdZOLENDPC_zol_0_i,
                     RdPC_zol_0_i,
                     RdZOLSTARTPC_zol_0_i,
  output wire [31:0] WrPC_zol_0_o,
  output wire        WrPC_validReq_zol_0_o,
  output wire [31:0] WrZOLCOUNTER_zol_0_o,
  output wire        WrZOLCOUNTER_validReq_zol_0_o
);

  wire _GEN = (|RdZOLCOUNTER_zol_0_i) & RdZOLENDPC_zol_0_i == RdPC_zol_0_i;	// @[scheduling_solutions.mlir:100:16, :103:16, :104:16]
  assign ready = 1'h1;	// @[scheduling_solutions.mlir:96:17]
  assign WrPC_zol_0_o = RdZOLSTARTPC_zol_0_i;
  assign WrPC_validReq_zol_0_o = _GEN;	// @[scheduling_solutions.mlir:104:16]
  assign WrZOLCOUNTER_zol_0_o = RdZOLCOUNTER_zol_0_i - 32'h1;	// @[scheduling_solutions.mlir:107:16]
  assign WrZOLCOUNTER_validReq_zol_0_o = _GEN;	// @[scheduling_solutions.mlir:104:16]
endmodule

