# Creates the CVA5 top module file based on the netlist generated by SCAIE-V.
# For arguments, see maketop.py

from maketop import write_top
import os

def translate_pin_name(name):
    # Identity, since no conversion step is required.
    return name

template_filename = "CVA5_top_template_bram.v"
write_top(template_filename, "CVA5_top.v", translate_pin_name)

