module testbench(
    input wire clk,
    input wire rst,
    input wire [31:0] irq_i,

    // BRAM Instruction
    output wire [31:0] m_bram_instr_addr,
    output wire        m_bram_instr_en,
    output wire [3:0]  m_bram_instr_we,
    output wire [31:0] m_bram_instr_din,
    input  wire [31:0] m_bram_instr_dout,

    // BRAM Data
    output wire [31:0] m_bram_data_addr,
    output wire        m_bram_data_en,
    output wire [3:0]  m_bram_data_we,
    output wire [31:0] m_bram_data_din,
    input  wire [31:0] m_bram_data_dout,

    // Generic LSU memory interface
    output wire dgeneric_new_request,
    output wire [31:0] dgeneric_addr,
    output wire dgeneric_re,
    output wire dgeneric_we,
    output wire [3:0] dgeneric_be,
    output wire [31:0] dgeneric_data_in,
    input wire [31:0] dgeneric_data_out,
    input wire dgeneric_data_valid,
    input wire dgeneric_ready,

    // Generic Fetch memory interface
    output wire igeneric_new_request,
    output wire [31:0] igeneric_addr,
    output wire igeneric_re,
    output wire igeneric_we,
    output wire [3:0] igeneric_be,
    output wire [31:0] igeneric_data_in,
    input wire [31:0] igeneric_data_out,
    input wire igeneric_data_valid,
    input wire igeneric_ready,

    //AXI Control Bus
    output wire         m_axi_ctrl_AWVALID,
    input  wire         m_axi_ctrl_AWREADY,
    output wire [5:0]   m_axi_ctrl_AWID,
    output wire [31:0]  m_axi_ctrl_AWADDR,
    output wire [2:0]   m_axi_ctrl_AWSIZE,
    output wire [7:0]   m_axi_ctrl_AWLEN,
    output wire [1:0]   m_axi_ctrl_AWBURST,

    output wire         m_axi_ctrl_WVALID,
    input  wire         m_axi_ctrl_WREADY,
    output wire [31:0]  m_axi_ctrl_WDATA,
    output wire [3:0]   m_axi_ctrl_WSTRB,
    output wire         m_axi_ctrl_WLAST,

    input  wire         m_axi_ctrl_BVALID,
    output wire         m_axi_ctrl_BREADY,
    input  wire [5:0]   m_axi_ctrl_BID,
    input  wire [1:0]   m_axi_ctrl_BRESP,

    output wire         m_axi_ctrl_ARVALID,
    input  wire         m_axi_ctrl_ARREADY,
    output wire [5:0]   m_axi_ctrl_ARID,
    output wire [31:0]  m_axi_ctrl_ARADDR,
    output wire [2:0]   m_axi_ctrl_ARSIZE,
    output wire [7:0]   m_axi_ctrl_ARLEN,
    output wire [1:0]   m_axi_ctrl_ARBURST,

    input  wire         m_axi_ctrl_RVALID,
    output wire         m_axi_ctrl_RREADY,
    input  wire [5:0]   m_axi_ctrl_RID,
    input  wire [31:0]  m_axi_ctrl_RDATA,
    input  wire [1:0]   m_axi_ctrl_RRESP,
    input  wire         m_axi_ctrl_RLAST
);

cva5_top  cva5_inst (
    .clk  (clk),
    .rst  (rst),
    .timer_interrupt(irq_i[7]),
    .interrupt(irq_i[3]),

    .instruction_bram_addr(m_bram_instr_addr),
    .instruction_bram_en  (m_bram_instr_en),
    .instruction_bram_we  (m_bram_instr_we),
    .instruction_bram_din (m_bram_instr_din),
    .instruction_bram_dout(m_bram_instr_dout),

    .data_bram_addr(m_bram_data_addr),
    .data_bram_en  (m_bram_data_en),
    .data_bram_we  (m_bram_data_we),
    .data_bram_din (m_bram_data_din),
    .data_bram_dout(m_bram_data_dout),

    // Generic LSU memory interface
    .dgeneric_new_request(dgeneric_new_request),
    .dgeneric_addr(dgeneric_addr),
    .dgeneric_re(dgeneric_re),
    .dgeneric_we(dgeneric_we),
    .dgeneric_be(dgeneric_be),
    .dgeneric_data_in(dgeneric_data_in),
    .dgeneric_data_out(dgeneric_data_out),
    .dgeneric_data_valid(dgeneric_data_valid),
    .dgeneric_ready(dgeneric_ready),

    // Generic Fetch memory interface
    .igeneric_new_request(igeneric_new_request),
    .igeneric_addr(igeneric_addr),
    .igeneric_re(igeneric_re),
    .igeneric_we(igeneric_we),
    .igeneric_be(igeneric_be),
    .igeneric_data_in(igeneric_data_in),
    .igeneric_data_out(igeneric_data_out),
    .igeneric_data_valid(igeneric_data_valid),
    .igeneric_ready(igeneric_ready),

    .m_axi_awvalid(m_axi_ctrl_AWVALID),
    .m_axi_awready(m_axi_ctrl_AWREADY),
    .m_axi_awid   (m_axi_ctrl_AWID),
    .m_axi_awaddr (m_axi_ctrl_AWADDR),
    .m_axi_awlen  (m_axi_ctrl_AWLEN),
    .m_axi_awsize (m_axi_ctrl_AWSIZE),
    .m_axi_awburst(m_axi_ctrl_AWBURST),
    .m_axi_awcache(),

    .m_axi_wvalid (m_axi_ctrl_WVALID),
    .m_axi_wready (m_axi_ctrl_WREADY),
    .m_axi_wdata  (m_axi_ctrl_WDATA),
    .m_axi_wstrb  (m_axi_ctrl_WSTRB),
    .m_axi_wlast  (m_axi_ctrl_WLAST),

    .m_axi_bvalid (m_axi_ctrl_BVALID),
    .m_axi_bready (m_axi_ctrl_BREADY),
    .m_axi_bid    (m_axi_ctrl_BID),
    .m_axi_bresp  (m_axi_ctrl_BRESP),

    .m_axi_arvalid(m_axi_ctrl_ARVALID),
    .m_axi_arready(m_axi_ctrl_ARREADY),
    .m_axi_arid   (m_axi_ctrl_ARID),
    .m_axi_araddr (m_axi_ctrl_ARADDR),
    .m_axi_arlen  (m_axi_ctrl_ARLEN),
    .m_axi_arsize (m_axi_ctrl_ARSIZE),
    .m_axi_arburst(m_axi_ctrl_ARBURST),
    .m_axi_arcache(),

    .m_axi_rvalid (m_axi_ctrl_RVALID),
    .m_axi_rready (m_axi_ctrl_RREADY),
    .m_axi_rid    (m_axi_ctrl_RID),
    .m_axi_rdata  (m_axi_ctrl_RDATA),
    .m_axi_rresp  (m_axi_ctrl_RRESP),
    .m_axi_rlast  (m_axi_ctrl_RLAST),

    // AXI Cache unused
    .m_axi_cache_awvalid(),
    .m_axi_cache_awready(1'b0),
    .m_axi_cache_awid(),
    .m_axi_cache_awaddr(),
    .m_axi_cache_awlen(),
    .m_axi_cache_awsize(),
    .m_axi_cache_awburst(),
    .m_axi_cache_awcache(),
    .m_axi_cache_awprot(),
    .m_axi_cache_wvalid(),
    .m_axi_cache_wready(1'b0),
    .m_axi_cache_wdata(),
    .m_axi_cache_wstrb(),
    .m_axi_cache_wlast(),
    .m_axi_cache_bvalid(1'b0),
    .m_axi_cache_bready(),
    .m_axi_cache_bresp(2'd0),
    .m_axi_cache_bid(6'd0),
    .m_axi_cache_arvalid(),
    .m_axi_cache_arready(1'b0),
    .m_axi_cache_arid(),
    .m_axi_cache_araddr(),
    .m_axi_cache_arlen(),
    .m_axi_cache_arsize(),
    .m_axi_cache_arburst(),
    .m_axi_cache_arcache(),
    .m_axi_cache_arprot(),
    .m_axi_cache_rvalid(1'b0),
    .m_axi_cache_rready(),
    .m_axi_cache_rid(6'd0),
    .m_axi_cache_rdata(32'd0),
    .m_axi_cache_rresp(2'd0),
    .m_axi_cache_rlast(1'b1)
);

endmodule
