# Creates the CVA6 top module file based on the netlist generated by SCAIE-V.
# For arguments, see maketop.py

from maketop import write_top

def translate_pin_name(name):
    # Identity, since no conversion step is required.
    return name
write_top("cva6_ariane_wrapper.sv", "cva6_ariane_wrapper.sv", translate_pin_name)

