# Creates the ORCA top module file based on the netlist generated by SCAIE-V.
# For arguments, see maketop.py

from maketop import write_top

def translate_pin_name(name):
    # Identity, since no conversion step is required.
    return name

write_top("ORCA_top_template.v", "ORCA_top.v", translate_pin_name)

