module testbench(
    input clk,
    input rst,

    //AXI Instruction Bus
    output logic         m_axi_instr_AWVALID,
    input  logic         m_axi_instr_AWREADY,
    output logic [31:0]  m_axi_instr_AWADDR,
    output logic [2:0]   m_axi_instr_AWSIZE,
    output logic [0:0]   m_axi_instr_AWID,
    output logic [7:0]   m_axi_instr_AWLEN,
    output logic [1:0]   m_axi_instr_AWBURST,

    output logic         m_axi_instr_WVALID,
    input  logic         m_axi_instr_WREADY,
    output logic [31:0]  m_axi_instr_WDATA,
    output logic [3:0]   m_axi_instr_WSTRB,
    output logic         m_axi_instr_WLAST,

    input  logic         m_axi_instr_BVALID,
    output logic         m_axi_instr_BREADY,
    input  logic [1:0]   m_axi_instr_BRESP,
    input  logic [0:0]   m_axi_instr_BID,

    output logic         m_axi_instr_ARVALID,
    input  logic         m_axi_instr_ARREADY,
    output logic [31:0]  m_axi_instr_ARADDR,
    output logic [2:0]   m_axi_instr_ARSIZE,
    output logic [0:0]   m_axi_instr_ARID,
    output logic [7:0]   m_axi_instr_ARLEN,
    output logic [1:0]   m_axi_instr_ARBURST,

    input  logic         m_axi_instr_RVALID,
    output logic         m_axi_instr_RREADY,
    input  logic [31:0]  m_axi_instr_RDATA,
    input  logic [1:0]   m_axi_instr_RRESP,
    input  logic [0:0]   m_axi_instr_RID,
    input  logic         m_axi_instr_RLAST,

    //AXI Data Bus
    output logic         m_axi_data_AWVALID,
    input  logic         m_axi_data_AWREADY,
    output logic [31:0]  m_axi_data_AWADDR,
    output logic [2:0]   m_axi_data_AWSIZE,
    output logic [0:0]   m_axi_data_AWID,
    output logic [7:0]   m_axi_data_AWLEN,
    output logic [1:0]   m_axi_data_AWBURST,

    output logic         m_axi_data_WVALID,
    input  logic         m_axi_data_WREADY,
    output logic [31:0]  m_axi_data_WDATA,
    output logic [3:0]   m_axi_data_WSTRB,
    output logic         m_axi_data_WLAST,

    input  logic         m_axi_data_BVALID,
    output logic         m_axi_data_BREADY,
    input  logic [1:0]   m_axi_data_BRESP,
    input  logic [0:0]   m_axi_data_BID,

    output logic         m_axi_data_ARVALID,
    input  logic         m_axi_data_ARREADY,
    output logic [31:0]  m_axi_data_ARADDR,
    output logic [2:0]   m_axi_data_ARSIZE,
    output logic [0:0]   m_axi_data_ARID,
    output logic [7:0]   m_axi_data_ARLEN,
    output logic [1:0]   m_axi_data_ARBURST,

    input  logic         m_axi_data_RVALID,
    output logic         m_axi_data_RREADY,
    input  logic [31:0]  m_axi_data_RDATA,
    input  logic [1:0]   m_axi_data_RRESP,
    input  logic [0:0]   m_axi_data_RID,
    input  logic         m_axi_data_RLAST
);

   top top_orca_inst (
        .IUC_ARID   (m_axi_instr_ARID   ),
        .IUC_ARADDR (m_axi_instr_ARADDR ),
        .IUC_ARLEN  (m_axi_instr_ARLEN  ),
        .IUC_ARSIZE (m_axi_instr_ARSIZE ),
        .IUC_ARBURST(m_axi_instr_ARBURST),
        .IUC_ARLOCK (),
        .IUC_ARCACHE(),
        .IUC_ARPROT (),
        .IUC_ARVALID(m_axi_instr_ARVALID),
        .IUC_ARREADY(m_axi_instr_ARREADY),
        .IUC_RID    (m_axi_instr_RID    ),
        .IUC_RDATA  (m_axi_instr_RDATA  ),
        .IUC_RRESP  (m_axi_instr_RRESP  ),
        .IUC_RLAST  (m_axi_instr_RLAST  ),
        .IUC_RVALID (m_axi_instr_RVALID ),
        .IUC_RREADY (m_axi_instr_RREADY ),
        .IUC_AWID   (m_axi_instr_AWID   ),
        .IUC_AWADDR (m_axi_instr_AWADDR ),
        .IUC_AWLEN  (m_axi_instr_AWLEN  ),
        .IUC_AWSIZE (m_axi_instr_AWSIZE ),
        .IUC_AWBURST(m_axi_instr_AWBURST),
        .IUC_AWLOCK (),
        .IUC_AWCACHE(),
        .IUC_AWPROT (),
        .IUC_AWVALID(m_axi_instr_AWVALID),
        .IUC_AWREADY(m_axi_instr_AWREADY),
        .IUC_WID    (),
        .IUC_WDATA  (m_axi_instr_WDATA  ),
        .IUC_WSTRB  (m_axi_instr_WSTRB  ),
        .IUC_WLAST  (m_axi_instr_WLAST  ),
        .IUC_WVALID (m_axi_instr_WVALID ),
        .IUC_WREADY (m_axi_instr_WREADY ),
        .IUC_BID    (m_axi_instr_BID    ),
        .IUC_BRESP  (m_axi_instr_BRESP  ),
        .IUC_BVALID (m_axi_instr_BVALID ),
        .IUC_BREADY (m_axi_instr_BREADY ),

        .DUC_AWID   (m_axi_data_AWID   ),
        .DUC_AWADDR (m_axi_data_AWADDR ),
        .DUC_AWLEN  (m_axi_data_AWLEN  ),
        .DUC_AWSIZE (m_axi_data_AWSIZE ),
        .DUC_AWBURST(m_axi_data_AWBURST),
        .DUC_AWLOCK (),
        .DUC_AWCACHE(),
        .DUC_AWPROT (),
        .DUC_AWVALID(m_axi_data_AWVALID),
        .DUC_AWREADY(m_axi_data_AWREADY),
        .DUC_WID    (),
        .DUC_WDATA  (m_axi_data_WDATA  ),
        .DUC_WSTRB  (m_axi_data_WSTRB  ),
        .DUC_WLAST  (m_axi_data_WLAST  ),
        .DUC_WVALID (m_axi_data_WVALID ),
        .DUC_WREADY (m_axi_data_WREADY ),
        .DUC_BID    (m_axi_data_BID    ),
        .DUC_BRESP  (m_axi_data_BRESP  ),
        .DUC_BVALID (m_axi_data_BVALID ),
        .DUC_BREADY (m_axi_data_BREADY ),
        .DUC_ARID   (m_axi_data_ARID   ),
        .DUC_ARADDR (m_axi_data_ARADDR ),
        .DUC_ARLEN  (m_axi_data_ARLEN  ),
        .DUC_ARSIZE (m_axi_data_ARSIZE ),
        .DUC_ARBURST(m_axi_data_ARBURST),
        .DUC_ARLOCK (),
        .DUC_ARCACHE(),
        .DUC_ARPROT (),
        .DUC_ARVALID(m_axi_data_ARVALID),
        .DUC_ARREADY(m_axi_data_ARREADY),
        .DUC_RID    (m_axi_data_RID    ),
        .DUC_RDATA  (m_axi_data_RDATA  ),
        .DUC_RRESP  (m_axi_data_RRESP  ),
        .DUC_RLAST  (m_axi_data_RLAST  ),
        .DUC_RVALID (m_axi_data_RVALID ),
        .DUC_RREADY (m_axi_data_RREADY ),

        .clk                        (clk),
        .rst                        (rst),
        .timer_interrupt            ('0),
        .timer_value                ('0),
        .global_interrupts          ('0));
endmodule
