# Creates the Piccolo top module file based on the netlist generated by SCAIE-V.
# For arguments, see maketop.py

from maketop import write_top

def translate_pin_name(name):
    return "met_v"+name+("_x" if name.endswith("_i") else "")

write_top("Piccolo_top_template.v", "Piccolo_top.v", translate_pin_name)

