#!/usr/bin/env python3
import os
import functools
import kconfiglib
import menuconfig
import shutil
import tempfile
import yaml
import re

import error
import run_cmd
from tools import sol_sel_to_yaml
from tools.critical_chains import export_chains_as_yaml

def run_menuconfig(kconf_path):
    kconf = kconfiglib.Kconfig(kconf_path)

    # Backup the current .config file to a temporary directory
    temp_dir = tempfile.mkdtemp()
    original_config_path = '.config'
    backup_config_path = os.path.join(temp_dir, '.config_backup')
    shutil.move(original_config_path, backup_config_path)

    # open menu config to let the user select the desired sharing groups
    menuconfig.menuconfig(kconf)

    # Restore the .config file
    shutil.move(backup_config_path, original_config_path)
    # Clean up the temporary directory
    shutil.rmtree(temp_dir)
    return kconf


def resolve_solver(kconfig_syms):
    for sym in kconfig_syms:
        if kconfig_syms[sym].str_value == "y" and str(sym).startswith("LN_SOLVER_USE_"):
            return str(sym)[len("LN_SOLVER_USE_"):]
    return None


def resolve_sched_algo(kconfig_syms):
    if kconfig_syms['LN_SCHED_ALGO_MS'].str_value == "y":
        sched_algo = ""
        if kconfig_syms['LN_SCHED_ALGO_MI'].str_value == "y":
            sched_algo = "MI_"
        if kconfig_syms['LN_SCHED_ALGO_PA'].str_value == "y":
            sched_algo += "PA"
        if kconfig_syms['LN_SCHED_ALGO_RA'].str_value == "y":
            sched_algo += "RA"

        sched_algo += "MS"
        return sched_algo
    return "LEGACY"


def resolve_opty_lib(kconfig_syms):
    # TODO these options could also be autogenerated!
    if kconfig_syms['LN_OPTY_NO_MODEL'].str_value == "y":
        return ""
    if kconfig_syms['LN_OPTY_OL2_MODEL'].str_value == "y":
        return os.path.abspath("deps/longnail/opTyLibraries/OL2.yaml")
    assert kconfig_syms['LN_OPTY_CUSTOM_MODEL'].str_value == "y"
    return os.path.abspath(kconfig_syms['LN_OPTY_CUSTOM_MODEL_PATH'].str_value)


def get_longnail_bin(kconf_syms, opt_prefix = "LN", fallback_folder = "longnail"):
    if kconf_syms[f"USE_PREBUILT_{opt_prefix}"].str_value == "y":
        ln_path = os.path.abspath(kconf_syms[f"{opt_prefix}_BINARY"].str_value)

        if not os.path.exists(ln_path):
            error.exit_error(f"Specified {fallback_folder} binary path '{ln_path}' does not exist!", error.USER_ERROR)

        return ln_path
    else:
        return os.path.abspath(f"deps/{fallback_folder}/build/bin/longnail-opt")

def prepare_scheduling(out_dir, ln_path, isax_mlir, prepared_sched_mlir_file, datasheet, kconfig_syms, skip_scheduling, show_ln_output):
    sched_algo = resolve_sched_algo(kconfig_syms)
    optylib = resolve_opty_lib(kconfig_syms)
    out_dir = os.path.abspath(out_dir)
    if kconfig_syms['LN_CELL_LIBRARY'].str_value:
        library = os.path.abspath(kconfig_syms['LN_CELL_LIBRARY'].str_value)
    else:
        library = ""

    # Sharing group selection is only necessary when sharing between instructions is enabled
    if "MI_" in sched_algo:
        sharing_group_sel_yaml = os.path.join(out_dir, "sharing_groups.yaml")
        if kconfig_syms['LN_PREDEFINED_SG_SELECTION'].str_value:
            sg_sel = os.path.abspath(kconfig_syms['LN_PREDEFINED_SG_SELECTION'].str_value)
            # Copy sg selection:
            shutil.copyfile(sg_sel, sharing_group_sel_yaml)
        else:
            run_cmd.run(out_dir, f"{ln_path} -export-sharing-groups=sharingGroupConfigPath={sharing_group_sel_yaml} {isax_mlir}", f"Longnail scheduling failed", error.LN_BASE + 5, show_ln_output, 200)

            # Load the original YAML
            with open(sharing_group_sel_yaml, "r") as f:
                instr_map = yaml.safe_load(f)

            # Remap group numbers to a dense range 1..N
            unique_groups = sorted(set(instr_map.values()))
            group_remap = {old: new for new, old in enumerate(unique_groups, start=1)}
            remapped_instr_map = {instr: group_remap[group] for instr, group in instr_map.items()}
            num_groups = len(unique_groups)

            # Create kconfig file
            sharing_group_sel_kconfig = os.path.join(out_dir, "sharing_groups.kconfig")
            with open(sharing_group_sel_kconfig, "w") as f:
                f.write("mainmenu \"Sharing Group Assignment\"\n")
                for instr, group in remapped_instr_map.items():
                    f.write("choice\n")
                    f.write(f"    prompt \"SG for {instr}\"\n")
                    f.write(f"    default SG_{group}_{instr}\n")
                    for i in range(1, num_groups + 1):
                        f.write(f"config SG_{i}_{instr}\n")
                        f.write("    bool\n")
                        f.write(f"    prompt \"SG {i}\"\n")
                    f.write("endchoice\n")
                #f.write("endmenu\n")

            kconf = run_menuconfig(sharing_group_sel_kconfig)

            # Update the isax map again
            for choice in kconf.choices:
                # Check the selected choice
                selected_sym = choice.selection
                assert (selected_sym)

                # Define the regex pattern with capture groups
                pattern = r"^SG_(\d+)_(\w+)$"

                # Search for the pattern in the string
                match = re.search(pattern, selected_sym.name)

                # Extract the numbers using the groups
                assert (match)
                sg_id = int(match.group(1))
                instr_name = match.group(2)
                assert (instr_name in remapped_instr_map)
                remapped_instr_map[instr_name] = sg_id

            # Save chosen mapping
            with open(sharing_group_sel_yaml, "w") as f:
                yaml.dump(remapped_instr_map, f)

        # Apply the chosen mapping
        run_cmd.run(out_dir, f"{ln_path} -import-sharing-groups=sharingGroupConfigPath={sharing_group_sel_yaml} {isax_mlir} -o {isax_mlir}", f"Longnail scheduling failed", error.LN_BASE + 6, show_ln_output, 200)

    longnail_prepare_schedule_flags = [
        "-coredsl-to-python",
        "-lower-coredsl-to-lil",
        f"-max-unroll-factor={kconfig_syms['LN_MAX_LOOP_UNROLL_FACTOR'].str_value}",
        f"-prepare-schedule-lil=\"datasheet={datasheet} library={library} opTyLibrary={optylib} schedulingAlgo={sched_algo}\"",
        f"-o {prepared_sched_mlir_file}",
    ]

    if not skip_scheduling:
        longnail_prep_flags_str = functools.reduce(
            lambda a, b: a+" "+b, longnail_prepare_schedule_flags)
        run_cmd.run(out_dir, f"{ln_path} {longnail_prep_flags_str} {isax_mlir}", f"Longnail scheduling preparation failed", error.LN_BASE + 7, show_ln_output, 200)

def run_scheduling(out_dir, ln_path, critical_chains, prepared_sched_mlir_file, sched_sol_mlir_file, sched_sol_kconf_file, iteration, kconfig_syms, show_ln_output):
    verbose = "false"
    if kconfig_syms['LN_VERBOSE_SCHEDULING'].str_value == "y":
        verbose = "true"
    ilp_solver = resolve_solver(kconfig_syms)

    chains_yaml_path = ""
    # Export the critical chains as yaml to be usable by LN
    if critical_chains:
        chains_yaml_path = os.path.abspath(os.path.join(out_dir, f"critical_chains_run_{iteration}.yaml"))
        export_chains_as_yaml(chains_yaml_path, critical_chains)

    longnail_schedule_flags = [
        f"-schedule-lil=\"chainPaths={chains_yaml_path} clockTime={kconfig_syms['LN_CLOCK_PERIOD'].str_value} solver={ilp_solver} schedulingTimeout={kconfig_syms['LN_SCHEDULE_TIMEOUT'].str_value} schedRefineTimeout={kconfig_syms['LN_REFINE_TIMEOUT'].str_value} solSelKconfPath={sched_sol_kconf_file} verbose={verbose}\"",
        f"-o {sched_sol_mlir_file}",
    ]
    if kconfig_syms['LN_DEBUG_SCHEDULING'].str_value == "y":
        longnail_schedule_flags.append("-debug-only=hw-sched")

    # execute LN
    longnail_sched_flags_str = functools.reduce(
        lambda a, b: a+" "+b, longnail_schedule_flags)
    run_cmd.run(out_dir, f"{ln_path} {longnail_sched_flags_str} {prepared_sched_mlir_file}", f"Longnail scheduling failed", error.LN_BASE + 8, show_ln_output, 200)
    return sched_sol_mlir_file, sched_sol_kconf_file


def run_hw_gen(out_dir, ln_path, sched_sol_mlir_file, sched_sol_kconf_file, sched_sol_config_file, sol_selection_file, kconfig_syms, show_ln_output):
    force_min_II_solutions = kconfig_syms['LN_FORCE_MIN_II_SOLUTIONS'].str_value == "y"
    if not force_min_II_solutions and kconfig_syms['LN_PREDEFINED_SOLUTION_SELECTION'].str_value:
        sol_selection_file = os.path.abspath(kconfig_syms['LN_PREDEFINED_SOLUTION_SELECTION'].str_value)
    elif not force_min_II_solutions and os.path.exists(sched_sol_kconf_file):
        kconf = run_menuconfig(sched_sol_kconf_file)
        # Then convert the selection to a yaml file for longnail to process
        sol_sel_to_yaml.convert_selection_to_yaml(kconf, sol_selection_file)
        # Note this is optional:
        kconf.write_config(sched_sol_config_file)
    else:
        force_min_II_solutions = True

    longnail_hw_gen_flags = [
        "-lower-lil-to-hw=forceUseMinIISolution=true" if force_min_II_solutions else f"-lower-lil-to-hw=solutionSelection={sol_selection_file}",
        "-simplify-structure", "-cse", "-print-stats",
        "-lower-seq-to-sv", "-hw-cleanup", "-cse", "-hw-legalize-modules", "-prettify-verilog",
        f"-export-split-verilog=dir-name={os.path.abspath(out_dir)}", "-o /dev/null"
    ]
    if kconfig_syms['LN_DEBUG_HWGEN'].str_value == "y":
        longnail_hw_gen_flags.append("-debug-only=hw-gen")
    if kconfig_syms['LN_DEBUG_PRINT_STATS'].str_value == "y":
        longnail_hw_gen_flags.append("-debug-only=print-stats")

    longnail_flags_str = functools.reduce(
        lambda a, b: a+" "+b, longnail_hw_gen_flags)
    run_cmd.run(out_dir, f"{ln_path} {longnail_flags_str} {sched_sol_mlir_file}", f"Longnail HW-Gen failed", error.LN_BASE + 9, show_ln_output, 200)

def run_longnail(mlir_paths, datasheet, kconfig_syms, out_dir, iteration, critical_chains):
    print("Running Longnail:")

    # check inputs
    try:
        float(kconfig_syms['LN_CLOCK_PERIOD'].str_value)
    except ValueError:
        error.exit_error(f"Target clock period='{kconfig_syms['LN_CLOCK_PERIOD'].str_value}' could not be converted to a floating point value!", error.USER_ERROR)

    is_first_iter = iteration == 0

    skip_scheduling = kconfig_syms["MLIR_ENTRY_POINT"].str_value == "y" and kconfig_syms["MLIR_ENTRY_POINT_IS_SCHEDULED"].str_value == "y"
    show_ln_output = kconfig_syms["LN_ALWAYS_SHOW_OUTPUT"].str_value == "y"

    ln_path = get_longnail_bin(kconfig_syms)
    datasheet = os.path.abspath(datasheet)

    prepared_sched_mlir_file = os.path.abspath(os.path.join(out_dir, "prepared_scheduling.mlir"))
    sched_sol_mlir_file = os.path.abspath(os.path.join(out_dir, f"scheduling_solutions_{iteration}.mlir"))
    sched_sol_kconf_file = os.path.abspath(os.path.join(out_dir, f"Kconfig_{iteration}"))
    sched_sol_config_file = os.path.abspath(os.path.join(out_dir, f".config_{iteration}"))
    sol_selection_file = os.path.abspath(os.path.join(out_dir, f"selected_solutions_{iteration}.yaml"))

    concated_isax_mlir = mlir_paths[0]
    if len(mlir_paths) > 1:
        concated_isax_mlir = os.path.abspath(os.path.join(out_dir, "pre_merged_isax.mlir"))
        if is_first_iter:
            with open(concated_isax_mlir, "w") as isax_mlir_file:
                for f in mlir_paths:
                    with open(f, "r") as fo:
                        isax_mlir_file.write(fo.read())
                os.fsync(isax_mlir_file)
    isax_mlir = os.path.abspath(os.path.join(out_dir, "merged_isax.mlir"))
    print(" - Merge ISAXes")
    run_cmd.run(out_dir, f"{ln_path} -merge-multiple-isaxes {concated_isax_mlir} -o {isax_mlir}", f"Longnail ISAX merging failed", error.LN_BASE + 4, show_ln_output, 200)

    if is_first_iter:
        print(" - Prepare for scheduling")
        prepare_scheduling(out_dir, ln_path, isax_mlir, prepared_sched_mlir_file, datasheet, kconfig_syms, skip_scheduling, show_ln_output)
    if not skip_scheduling:
        print(" - Run scheduling")
        sched_sol_mlir_file, sched_sol_kconf_file = run_scheduling(out_dir, ln_path, critical_chains, prepared_sched_mlir_file, sched_sol_mlir_file, sched_sol_kconf_file, iteration, kconfig_syms, show_ln_output)
    else:
        sched_sol_mlir_file = os.path.abspath(kconfig_syms["MLIR_ENTRY_POINT_PATH"].str_value)
        sched_sol_kconf_file = os.path.join(os.path.dirname(sched_sol_mlir_file), "Kconfig")

    print(" - Run HW generation")
    run_hw_gen(out_dir, ln_path, sched_sol_mlir_file, sched_sol_kconf_file, sched_sol_config_file, sol_selection_file, kconfig_syms, show_ln_output)

    return isax_mlir


def build_longnail(kconf_syms):
    if kconf_syms["USE_PREBUILT_LN"].str_value == "y":
        return

    # build longnail
    if not os.path.isfile("deps/longnail/build/bin/longnail-opt"):
        print("Building Longnail...")
        run_cmd.run("deps/longnail", "OR_TOOLS_VER=9.8 ./build_deps.sh",
                    "Gathering deps for CIRCT failed", error.LN_BASE + 1)
        run_cmd.run("deps/longnail", "./build_circt.sh",
                    "Building CIRCT failed", error.LN_BASE + 2)
        run_cmd.run("deps/longnail", "./build_longnail.sh",
                    "Longnail build failed", error.LN_BASE + 3)


# Selects the core datasheet file based on selected core
def select_core_datasheet(core_support):
    datasheet_folder = "deps/longnail/datasheets"
    datasheet_name = core_support.get_longnail_datasheet_name()
    if datasheet_name:
        return os.path.join(datasheet_folder, datasheet_name)
    else:
        error.exit_error(f"No LN datasheet found for the selected core!", error.USER_ERROR)


def provide_isax_yaml(out_dir):
    filelist = open(os.path.abspath(os.path.join(out_dir, "filelist.f")))
    yamls = [f[:-1] for f in filelist if f[-6:-1] == ".yaml"]
    return f"{out_dir}/"+yamls[0]
