// Generated by CIRCT unknown git version
module ISAX_dotprod_bias(	// @[/run_12/scheduling_solutions.mlir:2:3]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdRS1_DOTPBSET_2_i,
                     RdRS2_DOTPBSET_2_i,
  output wire [15:0] WrBIASES_DOTPBSET_2_o,
  output wire        WrBIASES_validReq_DOTPBSET_2_o,
  input  wire        RdStall_DOTPBSET_2_i,
                     RdIValid_DOTPBSET_2_i,
  input  wire [15:0] RdBIASES_DOTPB_2_i,
  input  wire [31:0] RdRS1_DOTPB_2_i,
                     RdRS2_DOTPB_2_i,
  output wire [31:0] WrRD_spawn_DOTPB_4_o,
  input  wire        WrRD_spawn_validResp_DOTPB_4_i,
                     Committed_rd_spawn_WrRD_spawn_4_i,
                     Committed_rd_spawn_validReq_WrRD_spawn_4_i,
                     RdStall_DOTPB_2_i,
                     RdIValid_DOTPB_2_i,
                     RdStall_DOTPB_3_i,
                     RdIValid_DOTPB_3_i
);

  wire _GEN;
  wire _GEN_0;
  wire _GEN_1;
  assign _GEN = RdIValid_DOTPBSET_2_i;
  assign _GEN = RdIValid_DOTPBSET_2_i;
  assign _GEN_0 = RdIValid_DOTPB_2_i;
  assign _GEN_1 = RdIValid_DOTPB_3_i;
  assign _GEN_0 = RdIValid_DOTPB_2_i;
  assign _GEN_1 = RdIValid_DOTPB_3_i;
  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("dotprod_bias.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_dotprod_bias_SharingGroup_1 inst_ISAX_dotprod_bias_SharingGroup_1 (
    .clk                            (clk_i),
    .rst                            (rst_i),
    .ready                          (/* unused */),
    .RdRS1_DOTPBSET_2_i             (RdRS1_DOTPBSET_2_i),
    .RdRS2_DOTPBSET_2_i             (RdRS2_DOTPBSET_2_i),
    .WrBIASES_DOTPBSET_2_o          (WrBIASES_DOTPBSET_2_o),
    .WrBIASES_validReq_DOTPBSET_2_o (WrBIASES_validReq_DOTPBSET_2_o),
    .RdStall_DOTPBSET_2_i           (RdStall_DOTPBSET_2_i),
    .RdIValid_DOTPBSET_2_i          (_GEN)
  );
  ISAX_dotprod_bias_SharingGroup_2 inst_ISAX_dotprod_bias_SharingGroup_2 (
    .clk                  (clk_i),
    .rst                  (rst_i),
    .ready                (/* unused */),
    .RdBIASES_DOTPB_2_i   (RdBIASES_DOTPB_2_i),
    .RdRS1_DOTPB_2_i      (RdRS1_DOTPB_2_i),
    .RdRS2_DOTPB_2_i      (RdRS2_DOTPB_2_i),
    .WrRD_spawn_DOTPB_4_o (WrRD_spawn_DOTPB_4_o),
    .RdStall_DOTPB_2_i    (RdStall_DOTPB_2_i),
    .RdIValid_DOTPB_2_i   (_GEN_0),
    .RdStall_DOTPB_3_i    (RdStall_DOTPB_3_i),
    .RdIValid_DOTPB_3_i   (_GEN_1)
  );
endmodule

module ISAX_dotprod_bias_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdRS1_DOTPBSET_2_i,
                     RdRS2_DOTPBSET_2_i,
  output wire [15:0] WrBIASES_DOTPBSET_2_o,
  output wire        WrBIASES_validReq_DOTPBSET_2_o,
  input  wire        RdStall_DOTPBSET_2_i,
                     RdIValid_DOTPBSET_2_i
);

  assign ready = 1'h1;
  assign WrBIASES_DOTPBSET_2_o = {RdRS2_DOTPBSET_2_i[7:0], RdRS1_DOTPBSET_2_i[7:0]};	// @[/run_12/scheduling_solutions.mlir:25:16, :27:16, :28:16]
  assign WrBIASES_validReq_DOTPBSET_2_o = 1'h1;
endmodule

module ISAX_dotprod_bias_SharingGroup_2(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [15:0] RdBIASES_DOTPB_2_i,
  input  wire [31:0] RdRS1_DOTPB_2_i,
                     RdRS2_DOTPB_2_i,
  output wire [31:0] WrRD_spawn_DOTPB_4_o,
  input  wire        RdStall_DOTPB_2_i,
                     RdIValid_DOTPB_2_i,
                     RdStall_DOTPB_3_i,
                     RdIValid_DOTPB_3_i
);

  wire [17:0] _inst_mul_18_res;	// @[/run_12/scheduling_solutions.mlir:215:17]
  wire [17:0] _inst_mul_18_res_0;	// @[/run_12/scheduling_solutions.mlir:208:17]
  wire [17:0] _inst_mul_18_res_1;	// @[/run_12/scheduling_solutions.mlir:201:17]
  wire [17:0] _inst_mul_18_res_2;	// @[/run_12/scheduling_solutions.mlir:194:16]
  wire [8:0]  _inst_sub_9_res;	// @[/run_12/scheduling_solutions.mlir:183:17]
  wire [8:0]  _inst_sub_9_res_0;	// @[/run_12/scheduling_solutions.mlir:179:17]
  wire [8:0]  _inst_sub_9_res_1;	// @[/run_12/scheduling_solutions.mlir:175:17]
  wire [8:0]  _inst_sub_9_res_2;	// @[/run_12/scheduling_solutions.mlir:171:17]
  wire [8:0]  _inst_sub_9_res_3;	// @[/run_12/scheduling_solutions.mlir:167:17]
  wire [8:0]  _inst_sub_9_res_4;	// @[/run_12/scheduling_solutions.mlir:163:17]
  wire [8:0]  _inst_sub_9_res_5;	// @[/run_12/scheduling_solutions.mlir:159:17]
  wire [8:0]  _inst_sub_9_res_6;	// @[/run_12/scheduling_solutions.mlir:151:17]
  wire        masked_stall_2_DOTPB =
    RdStall_DOTPB_2_i & RdIValid_DOTPB_2_i | RdStall_DOTPB_3_i & RdIValid_DOTPB_3_i;
  wire        masked_stall_3_DOTPB = RdStall_DOTPB_3_i & RdIValid_DOTPB_3_i;
  wire [8:0]  _GEN = {RdBIASES_DOTPB_2_i[7], RdBIASES_DOTPB_2_i[7:0]};	// @[/run_12/scheduling_solutions.mlir:146:16, :149:16, :150:16]
  wire [8:0]  _GEN_0 = {RdBIASES_DOTPB_2_i[15], RdBIASES_DOTPB_2_i[15:8]};	// @[/run_12/scheduling_solutions.mlir:154:17, :157:17, :158:17]
  sub_9 inst_sub_9 (	// @[/run_12/scheduling_solutions.mlir:151:17]
    .clk     (clk),
    .arg1    ({RdRS1_DOTPB_2_i[7], RdRS1_DOTPB_2_i[7:0]}),	// @[/run_12/scheduling_solutions.mlir:145:16, :147:16, :148:16]
    .arg2    (_GEN),	// @[/run_12/scheduling_solutions.mlir:150:16]
    .stall_0 (masked_stall_2_DOTPB),
    .res     (_inst_sub_9_res_6)
  );	// @[/run_12/scheduling_solutions.mlir:151:17]
  sub_9 inst_sub_9_0 (	// @[/run_12/scheduling_solutions.mlir:159:17]
    .clk     (clk),
    .arg1    ({RdRS2_DOTPB_2_i[7], RdRS2_DOTPB_2_i[7:0]}),	// @[/run_12/scheduling_solutions.mlir:153:17, :155:17, :156:17]
    .arg2    (_GEN_0),	// @[/run_12/scheduling_solutions.mlir:158:17]
    .stall_0 (masked_stall_2_DOTPB),
    .res     (_inst_sub_9_res_5)
  );	// @[/run_12/scheduling_solutions.mlir:159:17]
  sub_9 inst_sub_9_1 (	// @[/run_12/scheduling_solutions.mlir:163:17]
    .clk     (clk),
    .arg1    ({RdRS1_DOTPB_2_i[15], RdRS1_DOTPB_2_i[15:8]}),	// @[/run_12/scheduling_solutions.mlir:160:17, :161:17, :162:17]
    .arg2    (_GEN),	// @[/run_12/scheduling_solutions.mlir:150:16]
    .stall_0 (masked_stall_2_DOTPB),
    .res     (_inst_sub_9_res_4)
  );	// @[/run_12/scheduling_solutions.mlir:163:17]
  sub_9 inst_sub_9_2 (	// @[/run_12/scheduling_solutions.mlir:167:17]
    .clk     (clk),
    .arg1    ({RdRS2_DOTPB_2_i[15], RdRS2_DOTPB_2_i[15:8]}),	// @[/run_12/scheduling_solutions.mlir:164:17, :165:17, :166:17]
    .arg2    (_GEN_0),	// @[/run_12/scheduling_solutions.mlir:158:17]
    .stall_0 (masked_stall_2_DOTPB),
    .res     (_inst_sub_9_res_3)
  );	// @[/run_12/scheduling_solutions.mlir:167:17]
  sub_9 inst_sub_9_3 (	// @[/run_12/scheduling_solutions.mlir:171:17]
    .clk     (clk),
    .arg1    ({RdRS1_DOTPB_2_i[23], RdRS1_DOTPB_2_i[23:16]}),	// @[/run_12/scheduling_solutions.mlir:168:17, :169:17, :170:17]
    .arg2    (_GEN),	// @[/run_12/scheduling_solutions.mlir:150:16]
    .stall_0 (masked_stall_2_DOTPB),
    .res     (_inst_sub_9_res_2)
  );	// @[/run_12/scheduling_solutions.mlir:171:17]
  sub_9 inst_sub_9_4 (	// @[/run_12/scheduling_solutions.mlir:175:17]
    .clk     (clk),
    .arg1    ({RdRS2_DOTPB_2_i[23], RdRS2_DOTPB_2_i[23:16]}),	// @[/run_12/scheduling_solutions.mlir:172:17, :173:17, :174:17]
    .arg2    (_GEN_0),	// @[/run_12/scheduling_solutions.mlir:158:17]
    .stall_0 (masked_stall_2_DOTPB),
    .res     (_inst_sub_9_res_1)
  );	// @[/run_12/scheduling_solutions.mlir:175:17]
  sub_9 inst_sub_9_5 (	// @[/run_12/scheduling_solutions.mlir:179:17]
    .clk     (clk),
    .arg1    ({RdRS1_DOTPB_2_i[31], RdRS1_DOTPB_2_i[31:24]}),	// @[/run_12/scheduling_solutions.mlir:176:17, :177:17, :178:17]
    .arg2    (_GEN),	// @[/run_12/scheduling_solutions.mlir:150:16]
    .stall_0 (masked_stall_2_DOTPB),
    .res     (_inst_sub_9_res_0)
  );	// @[/run_12/scheduling_solutions.mlir:179:17]
  sub_9 inst_sub_9_6 (	// @[/run_12/scheduling_solutions.mlir:183:17]
    .clk     (clk),
    .arg1    ({RdRS2_DOTPB_2_i[31], RdRS2_DOTPB_2_i[31:24]}),	// @[/run_12/scheduling_solutions.mlir:180:17, :181:17, :182:17]
    .arg2    (_GEN_0),	// @[/run_12/scheduling_solutions.mlir:158:17]
    .stall_0 (masked_stall_2_DOTPB),
    .res     (_inst_sub_9_res)
  );	// @[/run_12/scheduling_solutions.mlir:183:17]
  mul_18 inst_mul_18 (	// @[/run_12/scheduling_solutions.mlir:194:16]
    .clk     (clk),
    .arg1    ({{9{_inst_sub_9_res_6[8]}}, _inst_sub_9_res_6}),	// @[/run_12/scheduling_solutions.mlir:151:17, :188:16, :189:16, :190:16]
    .arg2    ({{9{_inst_sub_9_res_5[8]}}, _inst_sub_9_res_5}),	// @[/run_12/scheduling_solutions.mlir:159:17, :191:16, :192:16, :193:16]
    .stall_0 (masked_stall_3_DOTPB),
    .res     (_inst_mul_18_res_2)
  );	// @[/run_12/scheduling_solutions.mlir:194:16]
  mul_18 inst_mul_18_0 (	// @[/run_12/scheduling_solutions.mlir:201:17]
    .clk     (clk),
    .arg1    ({{9{_inst_sub_9_res_4[8]}}, _inst_sub_9_res_4}),	// @[/run_12/scheduling_solutions.mlir:163:17, :195:16, :196:17, :197:17]
    .arg2    ({{9{_inst_sub_9_res_3[8]}}, _inst_sub_9_res_3}),	// @[/run_12/scheduling_solutions.mlir:167:17, :198:17, :199:17, :200:17]
    .stall_0 (masked_stall_3_DOTPB),
    .res     (_inst_mul_18_res_1)
  );	// @[/run_12/scheduling_solutions.mlir:201:17]
  mul_18 inst_mul_18_1 (	// @[/run_12/scheduling_solutions.mlir:208:17]
    .clk     (clk),
    .arg1    ({{9{_inst_sub_9_res_2[8]}}, _inst_sub_9_res_2}),	// @[/run_12/scheduling_solutions.mlir:171:17, :202:17, :203:17, :204:17]
    .arg2    ({{9{_inst_sub_9_res_1[8]}}, _inst_sub_9_res_1}),	// @[/run_12/scheduling_solutions.mlir:175:17, :205:17, :206:17, :207:17]
    .stall_0 (masked_stall_3_DOTPB),
    .res     (_inst_mul_18_res_0)
  );	// @[/run_12/scheduling_solutions.mlir:208:17]
  mul_18 inst_mul_18_2 (	// @[/run_12/scheduling_solutions.mlir:215:17]
    .clk     (clk),
    .arg1    ({{9{_inst_sub_9_res_0[8]}}, _inst_sub_9_res_0}),	// @[/run_12/scheduling_solutions.mlir:179:17, :209:17, :210:17, :211:17]
    .arg2    ({{9{_inst_sub_9_res[8]}}, _inst_sub_9_res}),	// @[/run_12/scheduling_solutions.mlir:183:17, :212:17, :213:17, :214:17]
    .stall_0 (masked_stall_3_DOTPB),
    .res     (_inst_mul_18_res)
  );	// @[/run_12/scheduling_solutions.mlir:215:17]
  assign ready = 1'h1;
  assign WrRD_spawn_DOTPB_4_o =
    {{14{_inst_mul_18_res_2[17]}}, _inst_mul_18_res_2}
    + {{14{_inst_mul_18_res_1[17]}}, _inst_mul_18_res_1}
    + {{14{_inst_mul_18_res_0[17]}}, _inst_mul_18_res_0}
    + {{14{_inst_mul_18_res[17]}}, _inst_mul_18_res};	// @[/run_12/scheduling_solutions.mlir:194:16, :201:17, :208:17, :215:17, :220:16, :221:16, :222:16, :223:16, :224:16, :225:16, :226:16, :227:16, :228:17, :229:17, :230:17, :231:17, :232:17, :233:17, :234:17]
endmodule

module sub_9(
  input  wire       clk,
  input  wire [8:0] arg1,
                    arg2,
  input  wire       stall_0,
  output wire [8:0] res
);

  reg [8:0] mockup_stage_1;
  always_ff @(posedge clk)
    mockup_stage_1 <= stall_0 ? mockup_stage_1 : arg1 - arg2;	// @[/run_12/scheduling_solutions.mlir:151:17]
  assign res = mockup_stage_1;
endmodule

module mul_18(
  input  wire        clk,
  input  wire [17:0] arg1,
                     arg2,
  input  wire        stall_0,
  output wire [17:0] res
);

  reg [17:0] mockup_stage_1;
  always_ff @(posedge clk)
    mockup_stage_1 <= stall_0 ? mockup_stage_1 : arg1 * arg2;	// @[/run_12/scheduling_solutions.mlir:194:16]
  assign res = mockup_stage_1;
endmodule

