// Generated by CIRCT unknown git version
module ISAX_dotprod(	// @[/run_1/scheduling_solutions_0.mlir:2:3]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdRS1_DOTP_2_i,
                     RdRS2_DOTP_2_i,
  output wire [31:0] WrRD_DOTP_3_o,
  input  wire        RdStall_DOTP_2_i,
                     RdIValid_DOTP_2_i,
                     RdStall_DOTP_3_i,
                     RdIValid_DOTP_3_i
);

  wire [31:0] _GEN;
  wire        _GEN_0 = clk_i;
  wire        _GEN_1 = rst_i;
  wire [31:0] _GEN_2 = RdRS1_DOTP_2_i;
  wire [31:0] _GEN_3 = RdRS2_DOTP_2_i;
  wire        _GEN_4 = RdStall_DOTP_2_i;
  wire        _GEN_5;
  wire        _GEN_6 = RdStall_DOTP_3_i;
  wire        _GEN_7;
  assign _GEN_5 = RdIValid_DOTP_2_i;
  assign _GEN_7 = RdIValid_DOTP_3_i;
  assign _GEN_7 = RdIValid_DOTP_3_i;
  assign _GEN_5 = RdIValid_DOTP_2_i;
  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("dotprod.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_dotprod_SharingGroup_1 inst_ISAX_dotprod_SharingGroup_1 (
    .clk               (_GEN_0),
    .rst               (_GEN_1),
    .ready             (/* unused */),
    .RdRS1_DOTP_2_i    (_GEN_2),
    .RdRS2_DOTP_2_i    (_GEN_3),
    .WrRD_DOTP_3_o     (_GEN),
    .RdStall_DOTP_2_i  (_GEN_4),
    .RdIValid_DOTP_2_i (_GEN_5),
    .RdStall_DOTP_3_i  (_GEN_6),
    .RdIValid_DOTP_3_i (_GEN_7)
  );
  assign WrRD_DOTP_3_o = _GEN;	// @[/run_1/scheduling_solutions_0.mlir:2:3]
endmodule

module ISAX_dotprod_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdRS1_DOTP_2_i,
                     RdRS2_DOTP_2_i,
  output wire [31:0] WrRD_DOTP_3_o,
  input  wire        RdStall_DOTP_2_i,
                     RdIValid_DOTP_2_i,
                     RdStall_DOTP_3_i,
                     RdIValid_DOTP_3_i
);

  reg  [31:0] lil_read_rs1_pipe_3;	// @[/run_1/scheduling_solutions_0.mlir:85:16]
  reg  [31:0] lil_read_rs2_pipe_3;	// @[/run_1/scheduling_solutions_0.mlir:86:16]
  wire        muxed_stall_3 =
    RdStall_DOTP_2_i & RdIValid_DOTP_2_i | RdStall_DOTP_3_i & RdIValid_DOTP_3_i;
  always_ff @(posedge clk) begin	// @[/run_1/scheduling_solutions_0.mlir:86:16]
    lil_read_rs1_pipe_3 <= muxed_stall_3 ? lil_read_rs1_pipe_3 : RdRS1_DOTP_2_i;	// @[/run_1/scheduling_solutions_0.mlir:85:16]
    lil_read_rs2_pipe_3 <= muxed_stall_3 ? lil_read_rs2_pipe_3 : RdRS2_DOTP_2_i;	// @[/run_1/scheduling_solutions_0.mlir:86:16]
  end // always_ff @(posedge)
  wire [15:0] _GEN =
    {{8{lil_read_rs1_pipe_3[7]}}, lil_read_rs1_pipe_3[7:0]}
    * /* LN_ID=12 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{8{lil_read_rs2_pipe_3[7]}},
                                                                                       lil_read_rs2_pipe_3[7:0]};	// @[/run_1/scheduling_solutions_0.mlir:85:16, :86:16, :93:16, :94:16, :95:16, :96:16, :97:16, :98:16, :99:16, :100:17, :101:17]
  wire [15:0] _GEN_0 =
    {{8{lil_read_rs1_pipe_3[15]}}, lil_read_rs1_pipe_3[15:8]}
    * /* LN_ID=22 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{8{lil_read_rs2_pipe_3[15]}},
                                                                                       lil_read_rs2_pipe_3[15:8]};	// @[/run_1/scheduling_solutions_0.mlir:85:16, :86:16, :103:17, :104:17, :105:17, :106:17, :107:17, :108:17, :109:17, :110:17, :111:17]
  wire [15:0] _GEN_1 =
    {{8{lil_read_rs1_pipe_3[23]}}, lil_read_rs1_pipe_3[23:16]}
    * /* LN_ID=36 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{8{lil_read_rs2_pipe_3[23]}},
                                                                                       lil_read_rs2_pipe_3[23:16]};	// @[/run_1/scheduling_solutions_0.mlir:85:16, :86:16, :117:17, :118:17, :119:17, :120:17, :121:17, :122:17, :123:17, :124:17, :125:17]
  wire [15:0] _GEN_2 =
    {{8{lil_read_rs1_pipe_3[31]}}, lil_read_rs1_pipe_3[31:24]}
    * /* LN_ID=48 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{8{lil_read_rs2_pipe_3[31]}},
                                                                                       lil_read_rs2_pipe_3[31:24]};	// @[/run_1/scheduling_solutions_0.mlir:85:16, :86:16, :129:17, :130:17, :131:17, :132:17, :133:17, :134:17, :135:17, :136:17, :137:17]
  assign ready = 1'h1;
  assign WrRD_DOTP_3_o =
    {{16{_GEN[15]}}, _GEN}
    + /* LN_ID=52 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{16{_GEN_0[15]}},
                                                                                       _GEN_0}
    + /* LN_ID=54 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{16{_GEN_1[15]}},
                                                                                       _GEN_1}
    + /* LN_ID=53 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{16{_GEN_2[15]}},
                                                                                       _GEN_2};	// @[/run_1/scheduling_solutions_0.mlir:101:17, :102:17, :111:17, :112:17, :113:17, :114:17, :115:17, :116:17, :125:17, :126:17, :127:17, :128:17, :137:17, :138:17, :139:17, :140:17, :141:17, :142:17, :143:17]
endmodule

