// Generated by CIRCT unknown git version
module ISAX_zol2d(	// @[/run_13/scheduling_solutions.mlir:2:3]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdRS1_setup_zol2dinner_2_i,
                     RdRS2_setup_zol2dinner_2_i,
  output wire [63:0] WrZOL2DPCSINNER_setup_zol2dinner_2_o,
  output wire        WrZOL2DPCSINNER_validReq_setup_zol2dinner_2_o,
  input  wire        RdStall_setup_zol2dinner_2_i,
                     RdIValid_setup_zol2dinner_2_i,
  input  wire [31:0] RdInstr_setup_zol2d_2_i,
                     RdPC_setup_zol2d_2_i,
  output wire [63:0] WrZOL2DPCSOUTER_setup_zol2d_2_o,
  output wire        WrZOL2DPCSOUTER_validReq_setup_zol2d_2_o,
  input  wire [31:0] RdRS1_setup_zol2d_2_i,
  output wire [15:0] WrZOL2DCOUNTERS_setup_zol2d_2_o,
  output wire        WrZOL2DCOUNTERS_validReq_setup_zol2d_2_o,
  output wire [7:0]  WrZOL2DBOUNDINNER_setup_zol2d_2_o,
  output wire        WrZOL2DBOUNDINNER_validReq_setup_zol2d_2_o,
  input  wire        RdStall_setup_zol2d_2_i,
                     RdIValid_setup_zol2d_2_i,
  input  wire [15:0] RdZOL2DCOUNTERS_zol2d_0_i,
  input  wire [63:0] RdZOL2DPCSINNER_zol2d_0_i,
                     RdZOL2DPCSOUTER_zol2d_0_i,
  input  wire [7:0]  RdZOL2DBOUNDINNER_zol2d_0_i,
  input  wire [31:0] RdPC_zol2d_0_i,
  output wire [31:0] WrPC_zol2d_0_o,
  output wire        WrPC_validReq_zol2d_0_o,
  output wire [15:0] WrZOL2DCOUNTERS_zol2d_0_o,
  output wire        WrZOL2DCOUNTERS_validReq_zol2d_0_o
);

  wire _GEN;
  wire _GEN_0;
  assign _GEN = RdIValid_setup_zol2dinner_2_i;
  assign _GEN = RdIValid_setup_zol2dinner_2_i;
  assign _GEN_0 = RdIValid_setup_zol2d_2_i;
  assign _GEN_0 = RdIValid_setup_zol2d_2_i;
  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("zol2d.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_zol2d_SharingGroup_1 inst_ISAX_zol2d_SharingGroup_1 (
    .clk                                           (clk_i),
    .rst                                           (rst_i),
    .ready                                         (/* unused */),
    .RdRS1_setup_zol2dinner_2_i                    (RdRS1_setup_zol2dinner_2_i),
    .RdRS2_setup_zol2dinner_2_i                    (RdRS2_setup_zol2dinner_2_i),
    .WrZOL2DPCSINNER_setup_zol2dinner_2_o          (WrZOL2DPCSINNER_setup_zol2dinner_2_o),
    .WrZOL2DPCSINNER_validReq_setup_zol2dinner_2_o
      (WrZOL2DPCSINNER_validReq_setup_zol2dinner_2_o),
    .RdStall_setup_zol2dinner_2_i                  (RdStall_setup_zol2dinner_2_i),
    .RdIValid_setup_zol2dinner_2_i                 (_GEN)
  );
  ISAX_zol2d_SharingGroup_2 inst_ISAX_zol2d_SharingGroup_2 (
    .clk                                        (clk_i),
    .rst                                        (rst_i),
    .ready                                      (/* unused */),
    .RdInstr_setup_zol2d_2_i                    (RdInstr_setup_zol2d_2_i),
    .RdPC_setup_zol2d_2_i                       (RdPC_setup_zol2d_2_i),
    .WrZOL2DPCSOUTER_setup_zol2d_2_o            (WrZOL2DPCSOUTER_setup_zol2d_2_o),
    .WrZOL2DPCSOUTER_validReq_setup_zol2d_2_o
      (WrZOL2DPCSOUTER_validReq_setup_zol2d_2_o),
    .RdRS1_setup_zol2d_2_i                      (RdRS1_setup_zol2d_2_i),
    .WrZOL2DCOUNTERS_setup_zol2d_2_o            (WrZOL2DCOUNTERS_setup_zol2d_2_o),
    .WrZOL2DCOUNTERS_validReq_setup_zol2d_2_o
      (WrZOL2DCOUNTERS_validReq_setup_zol2d_2_o),
    .WrZOL2DBOUNDINNER_setup_zol2d_2_o          (WrZOL2DBOUNDINNER_setup_zol2d_2_o),
    .WrZOL2DBOUNDINNER_validReq_setup_zol2d_2_o
      (WrZOL2DBOUNDINNER_validReq_setup_zol2d_2_o),
    .RdStall_setup_zol2d_2_i                    (RdStall_setup_zol2d_2_i),
    .RdIValid_setup_zol2d_2_i                   (_GEN_0)
  );
  ISAX_zol2d_SharingGroup_3 inst_ISAX_zol2d_SharingGroup_3 (
    .clk                                (clk_i),
    .rst                                (rst_i),
    .ready                              (/* unused */),
    .RdZOL2DCOUNTERS_zol2d_0_i          (RdZOL2DCOUNTERS_zol2d_0_i),
    .RdZOL2DPCSINNER_zol2d_0_i          (RdZOL2DPCSINNER_zol2d_0_i),
    .RdZOL2DPCSOUTER_zol2d_0_i          (RdZOL2DPCSOUTER_zol2d_0_i),
    .RdZOL2DBOUNDINNER_zol2d_0_i        (RdZOL2DBOUNDINNER_zol2d_0_i),
    .RdPC_zol2d_0_i                     (RdPC_zol2d_0_i),
    .WrPC_zol2d_0_o                     (WrPC_zol2d_0_o),
    .WrPC_validReq_zol2d_0_o            (WrPC_validReq_zol2d_0_o),
    .WrZOL2DCOUNTERS_zol2d_0_o          (WrZOL2DCOUNTERS_zol2d_0_o),
    .WrZOL2DCOUNTERS_validReq_zol2d_0_o (WrZOL2DCOUNTERS_validReq_zol2d_0_o)
  );
endmodule

module ISAX_zol2d_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdRS1_setup_zol2dinner_2_i,
                     RdRS2_setup_zol2dinner_2_i,
  output wire [63:0] WrZOL2DPCSINNER_setup_zol2dinner_2_o,
  output wire        WrZOL2DPCSINNER_validReq_setup_zol2dinner_2_o,
  input  wire        RdStall_setup_zol2dinner_2_i,
                     RdIValid_setup_zol2dinner_2_i
);

  assign ready = 1'h1;
  assign WrZOL2DPCSINNER_setup_zol2dinner_2_o =
    {RdRS2_setup_zol2dinner_2_i, RdRS1_setup_zol2dinner_2_i};	// @[/run_14/scheduling_solutions.mlir:97:16]
  assign WrZOL2DPCSINNER_validReq_setup_zol2dinner_2_o = 1'h1;
endmodule

module ISAX_zol2d_SharingGroup_2(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdInstr_setup_zol2d_2_i,
                     RdPC_setup_zol2d_2_i,
  output wire [63:0] WrZOL2DPCSOUTER_setup_zol2d_2_o,
  output wire        WrZOL2DPCSOUTER_validReq_setup_zol2d_2_o,
  input  wire [31:0] RdRS1_setup_zol2d_2_i,
  output wire [15:0] WrZOL2DCOUNTERS_setup_zol2d_2_o,
  output wire        WrZOL2DCOUNTERS_validReq_setup_zol2d_2_o,
  output wire [7:0]  WrZOL2DBOUNDINNER_setup_zol2d_2_o,
  output wire        WrZOL2DBOUNDINNER_validReq_setup_zol2d_2_o,
  input  wire        RdStall_setup_zol2d_2_i,
                     RdIValid_setup_zol2d_2_i
);

  assign ready = 1'h1;
  assign WrZOL2DPCSOUTER_setup_zol2d_2_o =
    {RdPC_setup_zol2d_2_i
       + {19'h0,
          RdInstr_setup_zol2d_2_i[31],
          RdInstr_setup_zol2d_2_i[7],
          RdInstr_setup_zol2d_2_i[30:25],
          RdInstr_setup_zol2d_2_i[11:8],
          1'h0},
     RdPC_setup_zol2d_2_i + 32'h4};	// @[/run_14/scheduling_solutions.mlir:54:16, :55:16, :56:16, :57:16, :59:16, :60:16, :61:16, :62:16]
  assign WrZOL2DPCSOUTER_validReq_setup_zol2d_2_o = 1'h1;
  assign WrZOL2DCOUNTERS_setup_zol2d_2_o = RdRS1_setup_zol2d_2_i[15:0];	// @[/run_14/scheduling_solutions.mlir:67:17]
  assign WrZOL2DCOUNTERS_validReq_setup_zol2d_2_o = 1'h1;
  assign WrZOL2DBOUNDINNER_setup_zol2d_2_o = RdRS1_setup_zol2d_2_i[7:0];	// @[/run_14/scheduling_solutions.mlir:66:17]
  assign WrZOL2DBOUNDINNER_validReq_setup_zol2d_2_o = 1'h1;
endmodule

module ISAX_zol2d_SharingGroup_3(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [15:0] RdZOL2DCOUNTERS_zol2d_0_i,
  input  wire [63:0] RdZOL2DPCSINNER_zol2d_0_i,
                     RdZOL2DPCSOUTER_zol2d_0_i,
  input  wire [7:0]  RdZOL2DBOUNDINNER_zol2d_0_i,
  input  wire [31:0] RdPC_zol2d_0_i,
  output wire [31:0] WrPC_zol2d_0_o,
  output wire        WrPC_validReq_zol2d_0_o,
  output wire [15:0] WrZOL2DCOUNTERS_zol2d_0_o,
  output wire        WrZOL2DCOUNTERS_validReq_zol2d_0_o
);

  wire _GEN = RdPC_zol2d_0_i == RdZOL2DPCSINNER_zol2d_0_i[63:32];	// @[/run_14/scheduling_solutions.mlir:163:16, :170:17]
  wire _GEN_0 =
    (|(RdZOL2DCOUNTERS_zol2d_0_i[15:8]))
    & RdPC_zol2d_0_i == RdZOL2DPCSOUTER_zol2d_0_i[63:32];	// @[/run_14/scheduling_solutions.mlir:159:16, :166:16, :177:17, :178:17, :179:17]
  wire _GEN_1 = (|(RdZOL2DCOUNTERS_zol2d_0_i[7:0])) ? _GEN : _GEN_0;	// @[/run_14/scheduling_solutions.mlir:160:16, :169:17, :170:17, :179:17, :186:17]
  assign ready = 1'h1;	// @[/run_14/scheduling_solutions.mlir:155:17]
  assign WrPC_zol2d_0_o =
    (|(RdZOL2DCOUNTERS_zol2d_0_i[7:0]))
      ? (_GEN ? RdZOL2DPCSINNER_zol2d_0_i[31:0] : RdPC_zol2d_0_i)
      : _GEN_0 ? RdZOL2DPCSOUTER_zol2d_0_i[31:0] : RdPC_zol2d_0_i;	// @[/run_14/scheduling_solutions.mlir:160:16, :162:16, :165:16, :169:17, :170:17, :171:17, :179:17, :180:17, :187:17]
  assign WrPC_validReq_zol2d_0_o = _GEN_1;	// @[/run_14/scheduling_solutions.mlir:186:17]
  assign WrZOL2DCOUNTERS_zol2d_0_o =
    (|(RdZOL2DCOUNTERS_zol2d_0_i[7:0]))
      ? {RdZOL2DCOUNTERS_zol2d_0_i[15:8],
         _GEN ? RdZOL2DCOUNTERS_zol2d_0_i[7:0] - 8'h1 : RdZOL2DBOUNDINNER_zol2d_0_i}
      : {_GEN_0
           ? RdZOL2DCOUNTERS_zol2d_0_i[15:8] - 8'h1
           : RdZOL2DCOUNTERS_zol2d_0_i[15:8],
         RdZOL2DBOUNDINNER_zol2d_0_i};	// @[/run_14/scheduling_solutions.mlir:159:16, :160:16, :169:17, :170:17, :172:17, :174:17, :175:17, :179:17, :181:17, :183:17, :184:17, :185:17]
  assign WrZOL2DCOUNTERS_validReq_zol2d_0_o = _GEN_1;	// @[/run_14/scheduling_solutions.mlir:186:17]
endmodule

