# VexRiscv_5s
!SerialCoreDescription
pipeline:
  name: root
  kind: root
  tags: []
  externalID: -1
  continuous: false
  nextStages: []
  children:
  - {name: fetch,     kind: core,      externalID: 0,  continuous: true, tags: [inorder], nextStages: [decode], children: []}
  - {name: decode,    kind: core,      externalID: 1,  continuous: true, tags: [inorder], nextStages: [execute], children: []}
  - {name: execute,   kind: core,      externalID: 2,  continuous: true, tags: [inorder], nextStages: [memory], children: []}
  - {name: memory,    kind: core,      externalID: 3,  continuous: true, tags: [inorder], nextStages: [writeback], children: []}
  - {name: writeback, kind: core,      externalID: 4,  continuous: true, tags: [inorder, commit], nextStages: [decoupled], children: []}
  - {name: decoupled, kind: decoupled, externalID: 5,  continuous: true, tags: [inorder], nextStages: [], children: []}
operations:
- operation: RdCustReg
  earliest: 1
  latency: 0
  latest: 4 
- operation: WrCustReg.addr
  earliest: 1
  latency: 0
  latest: 1
- operation: WrCustReg.data
  earliest: 1
  latency: 1
  costly: 2
- operation: RdRS1
  earliest: 2
  latency: 0
  latest: 4
  costly: 5
- operation: RdRS2
  earliest: 2
  latency: 0
  latest: 4
  costly: 5
- operation: WrRD
  earliest: 2
  latency: 1
  costly: 3
- operation: RdPC
  earliest: 1
  latency: 0
  costly: 4
- operation: WrPC
  earliest: 0
  latency: 1
  costly: 1
  latest: 4 
- operation: RdMem
  earliest: 2
  latency: 1
  costly: 3
- operation: WrMem
  earliest: 2
  latency: 1
  costly: 3
- operation: RdIValid
  earliest: 1
  latency: 0
  latest: 4
  costly: 5
- operation: RdInstr
  earliest: 1
  latency: 0
  latest: 4
  costly: 5
- operation: RdStall
  earliest: 1
  latency: 0
  latest: 4
  costly: 5
- operation: WrStall
  earliest: 1
  latency: 0
  latest: 4
  costly: 5
- operation: RdFlush
  earliest: 1
  latency: 0
  latest: 4
  costly: 5
- operation: WrFlush
  earliest: 1
  latency: 0
  latest: 4
  costly: 5
