# PicoRV32
!SerialCoreDescription
pipeline:
  name: root
  kind: root
  tags: []
  externalID: -1
  continuous: false
  nextStages: []
  # Pseudo-pipeline view on PicoRV32;
  # 'fetch' and 'writeback' both represent cpu_state_fetch, since the core does both in the same FSM state;
  # 'writeback' cannot be stalled nor flushed
  children:
  - {name: fetch,      kind: core,          externalID: 0,  continuous: true,  tags: [inorder, commit], nextStages: [rdregs], children: []}
  - {name: rdregs,     kind: core,          externalID: 1,  continuous: true,  tags: [inorder, commit], nextStages: [execute], children: []}
  - {name: execute,    kind: core,          externalID: 2,  continuous: true,  tags: [inorder, execute, commit], nextStages: [writeback], children: []}
  - {name: writeback,  kind: core,          externalID: 3,  continuous: true,  tags: [inorder, commit], nextStages: [decoupled1], children: []}
  - {name: decoupled1, kind: decoupled,     externalID: 4,  continuous: true,  tags: [inorder, commit], nextStages: [], children: []}
operations:
- operation: RdCustReg
  earliest: 0
  latency: 0
  latest: 3 
- operation: WrCustReg.addr
  earliest: 0
  latency: 0
  latest: 0
- operation: WrCustReg.data
  earliest: 0
  latency: 1
  costly: 1
- operation: RdRS1
  earliest: 1
  latency: 0
  latest: 1
  costly: 2
- operation: RdRS2
  earliest: 1
  latency: 0
  latest: 1
  costly: 2
- operation: WrRD
  earliest: 3
  latency: 1
  costly: 4
- operation: RdPC
  earliest: 0
  latest: 2
  costly: 3
  latency: 0
- operation: WrPC
  earliest: 0
  costly: 3
  latency: 1
  latest: 3
- operation: RdMem
  earliest: 2
  latency: 0 #data returned in same state
  costly: 3
- operation: WrMem
  earliest: 2
  latency: 0 
  costly: 3
- operation: RdIValid
  earliest: 0
  latency: 0
  latest: 3
  costly: 1
- operation: RdInstr
  earliest: 0
  latency: 0
  latest: 0
  costly: 1
- operation: RdStall
  earliest: 0
  latency: 0
  latest: 3
  costly: 4
- operation: WrStall
  earliest: 0
  latency: 0
  latest: 2
  costly: 3
- operation: RdFlush
  earliest: 0
  latency: 0
  latest: 3
  costly: 4
- operation: WrFlush
  earliest: 0
  latency: 0
  latest: 1
  costly: 4
