// Generated by CIRCT unknown git version
module ISAX_dotprod_single(	// @[/builds/scale4edge/nailgun/outputs/run_1/scheduling_solutions_0.mlir:2:3]
  input  wire        clk_i,
                     rst_i,
  input  wire [31:0] RdRS1_DOTP_4_i,
                     RdRS2_DOTP_4_i,
  output wire [31:0] WrRD_DOTP_4_o,
  input  wire        RdStall_DOTP_4_i,
                     RdIValid_DOTP_4_i
);

  wire        _GEN_0 = clk_i;
  wire        _GEN_1 = rst_i;
  `ifdef COCOTB_SIM
    `ifndef VERILATOR
      initial begin
        $dumpfile("dotprod.vcd"); $dumpvars;
      end // initial
    `endif // not def VERILATOR
  `endif // COCOTB_SIM
  ISAX_dotprod_single_SharingGroup_1 inst_ISAX_dotprod_SharingGroup_1 (
    .clk               (_GEN_0),
    .rst               (_GEN_1),
    .ready             (/* unused */),
    .RdRS1_DOTP_3_i    (RdRS1_DOTP_4_i),
    .RdRS2_DOTP_3_i    (RdRS2_DOTP_4_i),
    .WrRD_DOTP_3_o     (WrRD_DOTP_4_o),
    .RdStall_DOTP_3_i  (RdStall_DOTP_4_i),
    .RdIValid_DOTP_3_i (RdIValid_DOTP_4_i)
  );
endmodule

module ISAX_dotprod_single_SharingGroup_1(
  input  wire        clk,
                     rst,
  output wire        ready,
  input  wire [31:0] RdRS1_DOTP_3_i,
                     RdRS2_DOTP_3_i,
  output wire [31:0] WrRD_DOTP_3_o,
  input  wire        RdStall_DOTP_3_i,
                     RdIValid_DOTP_3_i
);

  wire [15:0] _GEN =
    {{8{RdRS1_DOTP_3_i[7]}}, RdRS1_DOTP_3_i[7:0]}
    * /* LN_ID=12 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{8{RdRS2_DOTP_3_i[7]}},
                                                                                       RdRS2_DOTP_3_i[7:0]};	// @[/builds/scale4edge/nailgun/outputs/run_1/scheduling_solutions_0.mlir:85:16, :86:16, :93:16, :94:16, :95:16, :96:16, :97:16, :98:16, :99:16, :100:17, :101:17]
  wire [15:0] _GEN_0 =
    {{8{RdRS1_DOTP_3_i[15]}}, RdRS1_DOTP_3_i[15:8]}
    * /* LN_ID=22 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{8{RdRS2_DOTP_3_i[15]}},
                                                                                       RdRS2_DOTP_3_i[15:8]};	// @[/builds/scale4edge/nailgun/outputs/run_1/scheduling_solutions_0.mlir:85:16, :86:16, :103:17, :104:17, :105:17, :106:17, :107:17, :108:17, :109:17, :110:17, :111:17]
  wire [15:0] _GEN_1 =
    {{8{RdRS1_DOTP_3_i[23]}}, RdRS1_DOTP_3_i[23:16]}
    * /* LN_ID=36 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{8{RdRS2_DOTP_3_i[23]}},
                                                                                       RdRS2_DOTP_3_i[23:16]};	// @[/builds/scale4edge/nailgun/outputs/run_1/scheduling_solutions_0.mlir:85:16, :86:16, :117:17, :118:17, :119:17, :120:17, :121:17, :122:17, :123:17, :124:17, :125:17]
  wire [15:0] _GEN_2 =
    {{8{RdRS1_DOTP_3_i[31]}}, RdRS1_DOTP_3_i[31:24]}
    * /* LN_ID=48 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{8{RdRS2_DOTP_3_i[31]}},
                                                                                       RdRS2_DOTP_3_i[31:24]};	// @[/builds/scale4edge/nailgun/outputs/run_1/scheduling_solutions_0.mlir:85:16, :86:16, :129:17, :130:17, :131:17, :132:17, :133:17, :134:17, :135:17, :136:17, :137:17]
  assign ready = 1'h1;
  assign WrRD_DOTP_3_o =
    {{16{_GEN[15]}}, _GEN}
    + /* LN_ID=52 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{16{_GEN_0[15]}},
                                                                                       _GEN_0}
    + /* LN_ID=54 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{16{_GEN_1[15]}},
                                                                                       _GEN_1}
    + /* LN_ID=53 PARENT_INST_NAME=[isax_dotprod_inst_ISAX_dotprod_SharingGroup_1] */ {{16{_GEN_2[15]}},
                                                                                       _GEN_2};	// @[/builds/scale4edge/nailgun/outputs/run_1/scheduling_solutions_0.mlir:101:17, :102:17, :111:17, :112:17, :113:17, :114:17, :115:17, :116:17, :125:17, :126:17, :127:17, :128:17, :137:17, :138:17, :139:17, :140:17, :141:17, :142:17, :143:17]
endmodule

